/* Generated by Cython 0.29.20 */

#ifndef __PYX_HAVE__pyoti__fem
#define __PYX_HAVE__pyoti__fem

#include "Python.h"

#ifndef __PYX_HAVE_API__pyoti__fem

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *alg;

#endif /* !__PYX_HAVE_API__pyoti__fem */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initfem(void);
#else
PyMODINIT_FUNC PyInit_fem(void);
#endif

#endif /* !__PYX_HAVE__pyoti__fem */
