MODULE OTIM10N1

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP         = 8
  INTEGER, PARAMETER :: NUM_IM_DIR = 11
  INTEGER, PARAMETER :: TORDER     = 1

  TYPE ONUMM10N1
    ! Real
    REAL(DP) :: R
    ! Order 1
    REAL(DP) :: E1
    REAL(DP) :: E2
    REAL(DP) :: E3
    REAL(DP) :: E4
    REAL(DP) :: E5
    REAL(DP) :: E6
    REAL(DP) :: E7
    REAL(DP) :: E8
    REAL(DP) :: E9
    REAL(DP) :: EA
  END TYPE ONUMM10N1

  INTERFACE OPERATOR(*)
    MODULE PROCEDURE ONUMM10N1_MUL_ONUMM10N1,R_MUL_ONUMM10N1,ONUMM10N1_MUL_R
  END INTERFACE

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE ONUMM10N1_ADD_ONUMM10N1,R_ADD_ONUMM10N1,ONUMM10N1_ADD_R
  END INTERFACE

  INTERFACE OPERATOR(-)
    MODULE PROCEDURE ONUMM10N1_NEG,ONUMM10N1_SUB_ONUMM10N1,R_SUB_ONUMM10N1,ONUMM10N1_SUB_R
  END INTERFACE

  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE ONUMM10N1_ASSIGN_R
  END INTERFACE

  INTERFACE TRANSPOSE
    MODULE PROCEDURE ONUMM10N1_TRANSPOSE
  END INTERFACE

  INTERFACE MATMUL
    MODULE PROCEDURE ONUMM10N1_MATMUL_ONUMM10N1,R_MATMUL_ONUMM10N1,ONUMM10N1_MATMUL_R
  END INTERFACE

  CONTAINS

  ELEMENTAL SUBROUTINE ONUMM10N1_ASSIGN_R(RES,LHS)
    
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1), INTENT(OUT) :: RES 

    ! Assign like function 'LHS'
    ! Real
    RES%R = LHS
    ! Order 1
    RES%E1 = 0.0_dp
    RES%E2 = 0.0_dp
    RES%E3 = 0.0_dp
    RES%E4 = 0.0_dp
    RES%E5 = 0.0_dp
    RES%E6 = 0.0_dp
    RES%E7 = 0.0_dp
    RES%E8 = 0.0_dp
    RES%E9 = 0.0_dp
    RES%EA = 0.0_dp

  END SUBROUTINE ONUMM10N1_ASSIGN_R

  ELEMENTAL FUNCTION ONUMM10N1_ADD_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS%R
    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3
    RES%E4 = LHS%E4 + RHS%E4
    RES%E5 = LHS%E5 + RHS%E5
    RES%E6 = LHS%E6 + RHS%E6
    RES%E7 = LHS%E7 + RHS%E7
    RES%E8 = LHS%E8 + RHS%E8
    RES%E9 = LHS%E9 + RHS%E9
    RES%EA = LHS%EA + RHS%EA

  END FUNCTION ONUMM10N1_ADD_ONUMM10N1

  ELEMENTAL FUNCTION R_ADD_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R
    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3
    RES%E4 =  + RHS%E4
    RES%E5 =  + RHS%E5
    RES%E6 =  + RHS%E6
    RES%E7 =  + RHS%E7
    RES%E8 =  + RHS%E8
    RES%E9 =  + RHS%E9
    RES%EA =  + RHS%EA

  END FUNCTION R_ADD_ONUMM10N1

  ELEMENTAL FUNCTION ONUMM10N1_ADD_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3
    RES%E4 = LHS%E4
    RES%E5 = LHS%E5
    RES%E6 = LHS%E6
    RES%E7 = LHS%E7
    RES%E8 = LHS%E8
    RES%E9 = LHS%E9
    RES%EA = LHS%EA

  END FUNCTION ONUMM10N1_ADD_R

  ELEMENTAL FUNCTION ONUMM10N1_NEG(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1) :: RES 

    ! Negation like function '-LHS'
    ! Real
    RES%R = -LHS%R
    ! Order 1
    RES%E1 = -LHS%E1
    RES%E2 = -LHS%E2
    RES%E3 = -LHS%E3
    RES%E4 = -LHS%E4
    RES%E5 = -LHS%E5
    RES%E6 = -LHS%E6
    RES%E7 = -LHS%E7
    RES%E8 = -LHS%E8
    RES%E9 = -LHS%E9
    RES%EA = -LHS%EA

  END FUNCTION ONUMM10N1_NEG

  ELEMENTAL FUNCTION ONUMM10N1_SUB_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS%R
    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3
    RES%E4 = LHS%E4 - RHS%E4
    RES%E5 = LHS%E5 - RHS%E5
    RES%E6 = LHS%E6 - RHS%E6
    RES%E7 = LHS%E7 - RHS%E7
    RES%E8 = LHS%E8 - RHS%E8
    RES%E9 = LHS%E9 - RHS%E9
    RES%EA = LHS%EA - RHS%EA

  END FUNCTION ONUMM10N1_SUB_ONUMM10N1

  ELEMENTAL FUNCTION R_SUB_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R
    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3
    RES%E4 =  - RHS%E4
    RES%E5 =  - RHS%E5
    RES%E6 =  - RHS%E6
    RES%E7 =  - RHS%E7
    RES%E8 =  - RHS%E8
    RES%E9 =  - RHS%E9
    RES%EA =  - RHS%EA

  END FUNCTION R_SUB_ONUMM10N1

  ELEMENTAL FUNCTION ONUMM10N1_SUB_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3
    RES%E4 = LHS%E4
    RES%E5 = LHS%E5
    RES%E6 = LHS%E6
    RES%E7 = LHS%E7
    RES%E8 = LHS%E8
    RES%E9 = LHS%E9
    RES%EA = LHS%EA

  END FUNCTION ONUMM10N1_SUB_R

  ELEMENTAL FUNCTION ONUMM10N1_MUL_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS%R*RHS%R
    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R
    RES%E4 = LHS%R*RHS%E4 + LHS%E4*RHS%R
    RES%E5 = LHS%R*RHS%E5 + LHS%E5*RHS%R
    RES%E6 = LHS%R*RHS%E6 + LHS%E6*RHS%R
    RES%E7 = LHS%R*RHS%E7 + LHS%E7*RHS%R
    RES%E8 = LHS%R*RHS%E8 + LHS%E8*RHS%R
    RES%E9 = LHS%R*RHS%E9 + LHS%E9*RHS%R
    RES%EA = LHS%R*RHS%EA + LHS%EA*RHS%R

  END FUNCTION ONUMM10N1_MUL_ONUMM10N1

  ELEMENTAL FUNCTION R_MUL_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS*RHS%R
    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3
    RES%E4 = LHS*RHS%E4
    RES%E5 = LHS*RHS%E5
    RES%E6 = LHS*RHS%E6
    RES%E7 = LHS*RHS%E7
    RES%E8 = LHS*RHS%E8
    RES%E9 = LHS*RHS%E9
    RES%EA = LHS*RHS%EA

  END FUNCTION R_MUL_ONUMM10N1

  ELEMENTAL FUNCTION ONUMM10N1_MUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM10N1) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS%R*RHS
    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS
    RES%E4 = LHS%E4*RHS
    RES%E5 = LHS%E5*RHS
    RES%E6 = LHS%E6*RHS
    RES%E7 = LHS%E7*RHS
    RES%E8 = LHS%E8*RHS
    RES%E9 = LHS%E9*RHS
    RES%EA = LHS%EA*RHS

  END FUNCTION ONUMM10N1_MUL_R

  FUNCTION ONUMM10N1_MATMUL_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM10N1) :: TMP 
    TYPE(ONUMM10N1) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION ONUMM10N1_MATMUL_ONUMM10N1

  FUNCTION R_MATMUL_ONUMM10N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM10N1), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM10N1) :: TMP 
    TYPE(ONUMM10N1) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION R_MATMUL_ONUMM10N1

  FUNCTION ONUMM10N1_MATMUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS(:,:) 
    REAL(DP), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM10N1) :: TMP 
    TYPE(ONUMM10N1) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION ONUMM10N1_MATMUL_R

  FUNCTION ONUMM10N1_TRANSPOSE(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM10N1), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM10N1) :: RES(SIZE(LHS,2),SIZE(LHS,1)) 
    INTEGER :: I,J 

    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(LHS,2)
        RES( J, I ) = LHS( I, J )
      END DO
    END DO

  END FUNCTION ONUMM10N1_TRANSPOSE

END MODULE OTIM10N1
