# This file only imports the dense version of OTI numbers.
# If required, use the sparse version of the library as

# import pyoti.core as pyoti
from pyoti.dense import *

# Version information. _version.py is generated by CMake from _version.py.in; the root VERSION file
# is the single source of truth shared with the C, Fortran and conda builds. Imported after the star
# import above so that the version attributes cannot be shadowed by the algebra modules.
from pyoti._version import __version__, __version_info__, version_number
