name: pyoti
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.13.*
  - numpy>=2.1,<3
  - scipy
  - cython>=3.0
  - pandas
  - make
  - cmake
  - pip
  - setuptools
  - pytest
  - ipykernel
  - conda-forge::pyvista
  - conda-forge::gmsh
  - conda-forge::python-gmsh
  - conda-forge::vtk<9.4
  - conda-forge::scikit-sparse
  - conda-forge::scikit-umfpack
