MODULE MDUALM3N3

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP         = 8
  INTEGER, PARAMETER :: NUM_IM_DIR = 8
  INTEGER, PARAMETER :: TORDER     = 3

  TYPE MDNUMM3N3
    ! Real
    REAL(DP) :: R
    ! Order 1
    REAL(DP) :: E1
    REAL(DP) :: E2
    REAL(DP) :: E3
    ! Order 2
    REAL(DP) :: E12
    REAL(DP) :: E13
    REAL(DP) :: E23
    ! Order 3
    REAL(DP) :: E123
  END TYPE MDNUMM3N3

  INTERFACE OPERATOR(*)
    MODULE PROCEDURE MDNUMM3N3_MUL_oo,MDNUMM3N3_MUL_Ro,MDNUMM3N3_MUL_oR
  END INTERFACE

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE MDNUMM3N3_ADD_oo,MDNUMM3N3_ADD_Ro,MDNUMM3N3_ADD_oR
  END INTERFACE

  INTERFACE OPERATOR(-)
    MODULE PROCEDURE MDNUMM3N3_NEG,MDNUMM3N3_SUB_oo,MDNUMM3N3_SUB_Ro,MDNUMM3N3_SUB_oR
  END INTERFACE

  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE MDNUMM3N3_ASSIGN_R
  END INTERFACE

  INTERFACE TRANSPOSE
    MODULE PROCEDURE MDNUMM3N3_TRANSPOSE
  END INTERFACE

  INTERFACE MATMUL
    MODULE PROCEDURE MDNUMM3N3_MATMUL_MDNUMM3N3,R_MATMUL_MDNUMM3N3,MDNUMM3N3_MATMUL_R
  END INTERFACE

  CONTAINS

  ELEMENTAL SUBROUTINE MDNUMM3N3_ASSIGN_R(RES,LHS)
    
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3), INTENT(OUT) :: RES 

    ! Assign like function 'LHS'
    ! Real
    RES%R = LHS
    ! Order 1
    RES%E1 = 0.0_dp
    RES%E2 = 0.0_dp
    RES%E3 = 0.0_dp
    ! Order 2
    RES%E12 = 0.0_dp
    RES%E13 = 0.0_dp
    RES%E23 = 0.0_dp
    ! Order 3
    RES%E123 = 0.0_dp

  END SUBROUTINE MDNUMM3N3_ASSIGN_R

  ELEMENTAL FUNCTION MDNUMM3N3_ADD_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R
    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3
    ! Order 2
    RES%E12 = LHS%E12 + RHS%E12
    RES%E13 = LHS%E13 + RHS%E13
    RES%E23 = LHS%E23 + RHS%E23
    ! Order 3
    RES%E123 = LHS%E123 + RHS%E123

  END FUNCTION MDNUMM3N3_ADD_oo

  ELEMENTAL FUNCTION MDNUMM3N3_ADD_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R
    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3
    ! Order 2
    RES%E12 =  + RHS%E12
    RES%E13 =  + RHS%E13
    RES%E23 =  + RHS%E23
    ! Order 3
    RES%E123 =  + RHS%E123

  END FUNCTION MDNUMM3N3_ADD_Ro

  ELEMENTAL FUNCTION MDNUMM3N3_ADD_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3
    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23
    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUMM3N3_ADD_oR

  ELEMENTAL FUNCTION MDNUMM3N3_NEG(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Negation like function '-LHS'
    ! Real
    RES%R = -LHS%R
    ! Order 1
    RES%E1 = -LHS%E1
    RES%E2 = -LHS%E2
    RES%E3 = -LHS%E3
    ! Order 2
    RES%E12 = -LHS%E12
    RES%E13 = -LHS%E13
    RES%E23 = -LHS%E23
    ! Order 3
    RES%E123 = -LHS%E123

  END FUNCTION MDNUMM3N3_NEG

  ELEMENTAL FUNCTION MDNUMM3N3_SUB_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R
    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3
    ! Order 2
    RES%E12 = LHS%E12 - RHS%E12
    RES%E13 = LHS%E13 - RHS%E13
    RES%E23 = LHS%E23 - RHS%E23
    ! Order 3
    RES%E123 = LHS%E123 - RHS%E123

  END FUNCTION MDNUMM3N3_SUB_oo

  ELEMENTAL FUNCTION MDNUMM3N3_SUB_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R
    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3
    ! Order 2
    RES%E12 =  - RHS%E12
    RES%E13 =  - RHS%E13
    RES%E23 =  - RHS%E23
    ! Order 3
    RES%E123 =  - RHS%E123

  END FUNCTION MDNUMM3N3_SUB_Ro

  ELEMENTAL FUNCTION MDNUMM3N3_SUB_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3
    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23
    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUMM3N3_SUB_oR

  ELEMENTAL FUNCTION MDNUMM3N3_MUL_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    !  Multiplication like function 'LHS*RHS'
    ! Order 0
    RES%R = LHS%R*RHS%R
    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R
    ! Order 2
    RES%E12 = LHS%R*RHS%E12 + LHS%E12*RHS%R + LHS%E1*RHS%E2 &
            + LHS%E2*RHS%E1
    RES%E13 = LHS%R*RHS%E13 + LHS%E13*RHS%R + LHS%E1*RHS%E3 &
            + LHS%E3*RHS%E1
    RES%E23 = LHS%R*RHS%E23 + LHS%E23*RHS%R + LHS%E2*RHS%E3 &
            + LHS%E3*RHS%E2
    ! Order 3
    RES%E123 = LHS%R*RHS%E123 + LHS%E123*RHS%R + LHS%E1*RHS%E23 &
             + LHS%E23*RHS%E1 + LHS%E2*RHS%E13 + LHS%E13*RHS%E2 &
             + LHS%E3*RHS%E12 + LHS%E12*RHS%E3

  END FUNCTION MDNUMM3N3_MUL_oo

  ELEMENTAL FUNCTION MDNUMM3N3_MUL_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R
    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3
    ! Order 2
    RES%E12 = LHS*RHS%E12
    RES%E13 = LHS*RHS%E13
    RES%E23 = LHS*RHS%E23
    ! Order 3
    RES%E123 = LHS*RHS%E123

  END FUNCTION MDNUMM3N3_MUL_Ro

  ELEMENTAL FUNCTION MDNUMM3N3_MUL_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(MDNUMM3N3) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS
    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS
    ! Order 2
    RES%E12 = LHS%E12*RHS
    RES%E13 = LHS%E13*RHS
    RES%E23 = LHS%E23*RHS
    ! Order 3
    RES%E123 = LHS%E123*RHS

  END FUNCTION MDNUMM3N3_MUL_oR

  FUNCTION MDNUMM3N3_MATMUL_MDNUMM3N3(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUMM3N3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    !  Multiplication like function 'MATMUL(LHS,RHS)'
    ! Order 0
    RES%R = MATMUL(LHS%R,RHS%R)
    ! Order 1
    RES%E1 = MATMUL(LHS%R,RHS%E1) + MATMUL(LHS%E1,RHS%R)
    RES%E2 = MATMUL(LHS%R,RHS%E2) + MATMUL(LHS%E2,RHS%R)
    RES%E3 = MATMUL(LHS%R,RHS%E3) + MATMUL(LHS%E3,RHS%R)
    ! Order 2
    RES%E12 = MATMUL(LHS%R,RHS%E12) + MATMUL(LHS%E12,RHS%R) + MATMUL(LHS%E1,RHS%E2) &
            + MATMUL(LHS%E2,RHS%E1)
    RES%E13 = MATMUL(LHS%R,RHS%E13) + MATMUL(LHS%E13,RHS%R) + MATMUL(LHS%E1,RHS%E3) &
            + MATMUL(LHS%E3,RHS%E1)
    RES%E23 = MATMUL(LHS%R,RHS%E23) + MATMUL(LHS%E23,RHS%R) + MATMUL(LHS%E2,RHS%E3) &
            + MATMUL(LHS%E3,RHS%E2)
    ! Order 3
    RES%E123 = MATMUL(LHS%R,RHS%E123) + MATMUL(LHS%E123,RHS%R) + MATMUL(LHS%E1,RHS%E23) &
             + MATMUL(LHS%E23,RHS%E1) + MATMUL(LHS%E2,RHS%E13) + MATMUL(LHS%E13,RHS%E2) &
             + MATMUL(LHS%E3,RHS%E12) + MATMUL(LHS%E12,RHS%E3)

  END FUNCTION MDNUMM3N3_MATMUL_MDNUMM3N3

  FUNCTION R_MATMUL_MDNUMM3N3(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUMM3N3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUMM3N3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS,RHS%R)
    ! Order 1
    RES%E1 = MATMUL(LHS,RHS%E1)
    RES%E2 = MATMUL(LHS,RHS%E2)
    RES%E3 = MATMUL(LHS,RHS%E3)
    ! Order 2
    RES%E12 = MATMUL(LHS,RHS%E12)
    RES%E13 = MATMUL(LHS,RHS%E13)
    RES%E23 = MATMUL(LHS,RHS%E23)
    ! Order 3
    RES%E123 = MATMUL(LHS,RHS%E123)

  END FUNCTION R_MATMUL_MDNUMM3N3

  FUNCTION MDNUMM3N3_MATMUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS(:,:)
    REAL(DP), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUMM3N3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS%R,RHS)
    ! Order 1
    RES%E1 = MATMUL(LHS%E1,RHS)
    RES%E2 = MATMUL(LHS%E2,RHS)
    RES%E3 = MATMUL(LHS%E3,RHS)
    ! Order 2
    RES%E12 = MATMUL(LHS%E12,RHS)
    RES%E13 = MATMUL(LHS%E13,RHS)
    RES%E23 = MATMUL(LHS%E23,RHS)
    ! Order 3
    RES%E123 = MATMUL(LHS%E123,RHS)

  END FUNCTION MDNUMM3N3_MATMUL_R

  FUNCTION MDNUMM3N3_TRANSPOSE(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM3N3), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUMM3N3) :: RES (SIZE(LHS,2),SIZE(LHS,1))

    ! Negation like function 'TRANSPOSE(LHS)'
    ! Real
    RES%R = TRANSPOSE(LHS%R)
    ! Order 1
    RES%E1 = TRANSPOSE(LHS%E1)
    RES%E2 = TRANSPOSE(LHS%E2)
    RES%E3 = TRANSPOSE(LHS%E3)
    ! Order 2
    RES%E12 = TRANSPOSE(LHS%E12)
    RES%E13 = TRANSPOSE(LHS%E13)
    RES%E23 = TRANSPOSE(LHS%E23)
    ! Order 3
    RES%E123 = TRANSPOSE(LHS%E123)

  END FUNCTION MDNUMM3N3_TRANSPOSE

END MODULE MDUALM3N3
