MODULE MDUAL3

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP         = 8
  INTEGER, PARAMETER :: NUM_IM_DIR = 8
  INTEGER, PARAMETER :: TORDER     = 3

  TYPE MDNUM3
    ! Real
    REAL(DP) :: R
    ! Order 1
    REAL(DP) :: E1
    REAL(DP) :: E2
    REAL(DP) :: E3
    ! Order 2
    REAL(DP) :: E12
    REAL(DP) :: E13
    REAL(DP) :: E23
    ! Order 3
    REAL(DP) :: E123
  END TYPE MDNUM3

  ! Constant imaginary directions.
  ! Order 1
  TYPE(MDNUM3), PARAMETER :: E1 = MDNUM3(0.0_DP,1.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP)
  TYPE(MDNUM3), PARAMETER :: E2 = MDNUM3(0.0_DP,0.0_DP,1.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP)
  TYPE(MDNUM3), PARAMETER :: E3 = MDNUM3(0.0_DP,0.0_DP,0.0_DP,1.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP)
  ! Order 2
  TYPE(MDNUM3), PARAMETER :: E12 = MDNUM3(0.0_DP,0.0_DP,0.0_DP,0.0_DP,1.0_DP,0.0_DP,0.0_DP,0.0_DP)
  TYPE(MDNUM3), PARAMETER :: E13 = MDNUM3(0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,1.0_DP,0.0_DP,0.0_DP)
  TYPE(MDNUM3), PARAMETER :: E23 = MDNUM3(0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,1.0_DP,0.0_DP)
  ! Order 3
  TYPE(MDNUM3), PARAMETER :: E123 = MDNUM3(0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,0.0_DP,1.0_DP)

  PRIVATE :: DP,TORDER,DER_R_COS, &
             DER_R_SIN,DER_R_LOG,DER_R_EXP,DER_R_POW

  INTERFACE OPERATOR(*)
    MODULE PROCEDURE MDNUM3_MUL_OO_SS,MDNUM3_MUL_RO_SS,MDNUM3_MUL_OR_SS,MDNUM3_MUL_OO_VS,&
                     MDNUM3_MUL_RO_VS,MDNUM3_MUL_OR_VS,MDNUM3_MUL_OO_MS,MDNUM3_MUL_RO_MS,&
                     MDNUM3_MUL_OR_MS,MDNUM3_MUL_OO_SV,MDNUM3_MUL_RO_SV,MDNUM3_MUL_OR_SV,&
                     MDNUM3_MUL_OO_SM,MDNUM3_MUL_RO_SM,MDNUM3_MUL_OR_SM
  END INTERFACE

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE MDNUM3_ADD_OO_SS,MDNUM3_ADD_RO_SS,MDNUM3_ADD_OR_SS,MDNUM3_ADD_OO_VS,&
                     MDNUM3_ADD_RO_VS,MDNUM3_ADD_OR_VS,MDNUM3_ADD_OO_MS,MDNUM3_ADD_RO_MS,&
                     MDNUM3_ADD_OR_MS,MDNUM3_ADD_OO_SV,MDNUM3_ADD_RO_SV,MDNUM3_ADD_OR_SV,&
                     MDNUM3_ADD_OO_SM,MDNUM3_ADD_RO_SM,MDNUM3_ADD_OR_SM
  END INTERFACE

  INTERFACE OPERATOR(-)
    MODULE PROCEDURE MDNUM3_NEG,MDNUM3_SUB_OO_SS,MDNUM3_SUB_RO_SS,MDNUM3_SUB_OR_SS,&
                     MDNUM3_SUB_OO_VS,MDNUM3_SUB_RO_VS,MDNUM3_SUB_OR_VS,MDNUM3_SUB_OO_MS,&
                     MDNUM3_SUB_RO_MS,MDNUM3_SUB_OR_MS,MDNUM3_SUB_OO_SV,MDNUM3_SUB_RO_SV,&
                     MDNUM3_SUB_OR_SV,MDNUM3_SUB_OO_SM,MDNUM3_SUB_RO_SM,MDNUM3_SUB_OR_SM
  END INTERFACE

  INTERFACE OPERATOR(/)
    MODULE PROCEDURE MDNUM3_DIVISION_OO,MDNUM3_DIVISION_OR,MDNUM3_DIVISION_RO
  END INTERFACE

  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE MDNUM3_ASSIGN_R
  END INTERFACE

  INTERFACE OPERATOR(**)
    MODULE PROCEDURE MDNUM3_POW
  END INTERFACE

  INTERFACE PPRINT
    MODULE PROCEDURE MDNUM3_PPRINT_M_R
  END INTERFACE

  INTERFACE TRANSPOSE
    MODULE PROCEDURE MDNUM3_TRANSPOSE
  END INTERFACE

  INTERFACE MATMUL
    MODULE PROCEDURE MDNUM3_MATMUL_MDNUM3,R_MATMUL_MDNUM3,MDNUM3_MATMUL_R
  END INTERFACE

  INTERFACE UNFOLD
    MODULE PROCEDURE MDNUM3_TO_CR_MAT_S,MDNUM3_TO_CR_MAT_V,MDNUM3_TO_CR_MAT_M
  END INTERFACE

  INTERFACE TO_CR
    MODULE PROCEDURE MDNUM3_TO_CR_MAT_S,MDNUM3_TO_CR_MAT_V,MDNUM3_TO_CR_MAT_M
  END INTERFACE

  INTERFACE SIN
    MODULE PROCEDURE MDNUM3_SIN
  END INTERFACE

  INTERFACE COS
    MODULE PROCEDURE MDNUM3_COS
  END INTERFACE

  INTERFACE SQRT
    MODULE PROCEDURE MDNUM3_SQRT
  END INTERFACE

  INTERFACE LOG
    MODULE PROCEDURE MDNUM3_LOG
  END INTERFACE

  INTERFACE EXP
    MODULE PROCEDURE MDNUM3_EXP
  END INTERFACE

  INTERFACE GEM
    MODULE PROCEDURE MDNUM3_GEM_OOO,MDNUM3_GEM_ROO,MDNUM3_GEM_ORO
  END INTERFACE

  INTERFACE FEVAL
    MODULE PROCEDURE MDNUM3_FEVAL
  END INTERFACE

  INTERFACE REAL
    MODULE PROCEDURE MDNUM3_REAL
  END INTERFACE

  CONTAINS

  ELEMENTAL SUBROUTINE MDNUM3_ASSIGN_R(RES,LHS)
    
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUM3), INTENT(OUT) :: RES 

    ! Assign like function 'LHS'
    ! Real
    RES%R = LHS

    ! Order 1
    RES%E1 = 0.0_DP
    RES%E2 = 0.0_DP
    RES%E3 = 0.0_DP

    ! Order 2
    RES%E12 = 0.0_DP
    RES%E13 = 0.0_DP
    RES%E23 = 0.0_DP

    ! Order 3
    RES%E123 = 0.0_DP

  END SUBROUTINE MDNUM3_ASSIGN_R

  ELEMENTAL FUNCTION MDNUM3_NEG(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS 
    TYPE(MDNUM3) :: RES 

    ! Negation like function '-LHS'
    ! Real
    RES%R = -LHS%R
    ! Order 1
    RES%E1 = -LHS%E1
    RES%E2 = -LHS%E2
    RES%E3 = -LHS%E3
    ! Order 2
    RES%E12 = -LHS%E12
    RES%E13 = -LHS%E13
    RES%E23 = -LHS%E23
    ! Order 3
    RES%E123 = -LHS%E123

  END FUNCTION MDNUM3_NEG

  ELEMENTAL FUNCTION MDNUM3_ADD_OO_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R

    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 + RHS%E12
    RES%E13 = LHS%E13 + RHS%E13
    RES%E23 = LHS%E23 + RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 + RHS%E123

  END FUNCTION MDNUM3_ADD_OO_SS

  ELEMENTAL FUNCTION MDNUM3_ADD_RO_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R

    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3

    ! Order 2
    RES%E12 =  + RHS%E12
    RES%E13 =  + RHS%E13
    RES%E23 =  + RHS%E23

    ! Order 3
    RES%E123 =  + RHS%E123

  END FUNCTION MDNUM3_ADD_RO_SS

  ELEMENTAL FUNCTION MDNUM3_ADD_OR_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_ADD_OR_SS

  ELEMENTAL FUNCTION MDNUM3_SUB_OO_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R

    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 - RHS%E12
    RES%E13 = LHS%E13 - RHS%E13
    RES%E23 = LHS%E23 - RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 - RHS%E123

  END FUNCTION MDNUM3_SUB_OO_SS

  ELEMENTAL FUNCTION MDNUM3_SUB_RO_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R

    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3

    ! Order 2
    RES%E12 =  - RHS%E12
    RES%E13 =  - RHS%E13
    RES%E23 =  - RHS%E23

    ! Order 3
    RES%E123 =  - RHS%E123

  END FUNCTION MDNUM3_SUB_RO_SS

  ELEMENTAL FUNCTION MDNUM3_SUB_OR_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_SUB_OR_SS

  ELEMENTAL FUNCTION MDNUM3_MUL_OO_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    !  Multiplication like function 'LHS*RHS'

    ! Order 0
    RES%R = LHS%R*RHS%R

    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R

    ! Order 2
    RES%E12 = LHS%R*RHS%E12 + LHS%E12*RHS%R + LHS%E1*RHS%E2 &
            + LHS%E2*RHS%E1
    RES%E13 = LHS%R*RHS%E13 + LHS%E13*RHS%R + LHS%E1*RHS%E3 &
            + LHS%E3*RHS%E1
    RES%E23 = LHS%R*RHS%E23 + LHS%E23*RHS%R + LHS%E2*RHS%E3 &
            + LHS%E3*RHS%E2

    ! Order 3
    RES%E123 = LHS%R*RHS%E123 + LHS%E123*RHS%R + LHS%E1*RHS%E23 &
             + LHS%E23*RHS%E1 + LHS%E2*RHS%E13 + LHS%E13*RHS%E2 &
             + LHS%E3*RHS%E12 + LHS%E12*RHS%E3

  END FUNCTION MDNUM3_MUL_OO_SS

  ELEMENTAL FUNCTION MDNUM3_MUL_RO_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R

    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3

    ! Order 2
    RES%E12 = LHS*RHS%E12
    RES%E13 = LHS*RHS%E13
    RES%E23 = LHS*RHS%E23

    ! Order 3
    RES%E123 = LHS*RHS%E123

  END FUNCTION MDNUM3_MUL_RO_SS

  ELEMENTAL FUNCTION MDNUM3_MUL_OR_SS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS

    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS

    ! Order 2
    RES%E12 = LHS%E12*RHS
    RES%E13 = LHS%E13*RHS
    RES%E23 = LHS%E23*RHS

    ! Order 3
    RES%E123 = LHS%E123*RHS

  END FUNCTION MDNUM3_MUL_OR_SS

  FUNCTION MDNUM3_ADD_OO_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R

    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 + RHS%E12
    RES%E13 = LHS%E13 + RHS%E13
    RES%E23 = LHS%E23 + RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 + RHS%E123

  END FUNCTION MDNUM3_ADD_OO_VS

  FUNCTION MDNUM3_ADD_RO_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R

    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3

    ! Order 2
    RES%E12 =  + RHS%E12
    RES%E13 =  + RHS%E13
    RES%E23 =  + RHS%E23

    ! Order 3
    RES%E123 =  + RHS%E123

  END FUNCTION MDNUM3_ADD_RO_VS

  FUNCTION MDNUM3_ADD_OR_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:)
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_ADD_OR_VS

  FUNCTION MDNUM3_SUB_OO_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R

    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 - RHS%E12
    RES%E13 = LHS%E13 - RHS%E13
    RES%E23 = LHS%E23 - RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 - RHS%E123

  END FUNCTION MDNUM3_SUB_OO_VS

  FUNCTION MDNUM3_SUB_RO_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R

    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3

    ! Order 2
    RES%E12 =  - RHS%E12
    RES%E13 =  - RHS%E13
    RES%E23 =  - RHS%E23

    ! Order 3
    RES%E123 =  - RHS%E123

  END FUNCTION MDNUM3_SUB_RO_VS

  FUNCTION MDNUM3_SUB_OR_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:)
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_SUB_OR_VS

  FUNCTION MDNUM3_MUL_OO_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    !  Multiplication like function 'LHS*RHS'

    ! Order 0
    RES%R = LHS%R*RHS%R

    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R

    ! Order 2
    RES%E12 = LHS%R*RHS%E12 + LHS%E12*RHS%R + LHS%E1*RHS%E2 &
            + LHS%E2*RHS%E1
    RES%E13 = LHS%R*RHS%E13 + LHS%E13*RHS%R + LHS%E1*RHS%E3 &
            + LHS%E3*RHS%E1
    RES%E23 = LHS%R*RHS%E23 + LHS%E23*RHS%R + LHS%E2*RHS%E3 &
            + LHS%E3*RHS%E2

    ! Order 3
    RES%E123 = LHS%R*RHS%E123 + LHS%E123*RHS%R + LHS%E1*RHS%E23 &
             + LHS%E23*RHS%E1 + LHS%E2*RHS%E13 + LHS%E13*RHS%E2 &
             + LHS%E3*RHS%E12 + LHS%E12*RHS%E3

  END FUNCTION MDNUM3_MUL_OO_VS

  FUNCTION MDNUM3_MUL_RO_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R

    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3

    ! Order 2
    RES%E12 = LHS*RHS%E12
    RES%E13 = LHS*RHS%E13
    RES%E23 = LHS*RHS%E23

    ! Order 3
    RES%E123 = LHS*RHS%E123

  END FUNCTION MDNUM3_MUL_RO_VS

  FUNCTION MDNUM3_MUL_OR_VS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:)
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS

    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS

    ! Order 2
    RES%E12 = LHS%E12*RHS
    RES%E13 = LHS%E13*RHS
    RES%E23 = LHS%E23*RHS

    ! Order 3
    RES%E123 = LHS%E123*RHS

  END FUNCTION MDNUM3_MUL_OR_VS

  FUNCTION MDNUM3_ADD_OO_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R

    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 + RHS%E12
    RES%E13 = LHS%E13 + RHS%E13
    RES%E23 = LHS%E23 + RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 + RHS%E123

  END FUNCTION MDNUM3_ADD_OO_MS

  FUNCTION MDNUM3_ADD_RO_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R

    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3

    ! Order 2
    RES%E12 =  + RHS%E12
    RES%E13 =  + RHS%E13
    RES%E23 =  + RHS%E23

    ! Order 3
    RES%E123 =  + RHS%E123

  END FUNCTION MDNUM3_ADD_RO_MS

  FUNCTION MDNUM3_ADD_OR_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_ADD_OR_MS

  FUNCTION MDNUM3_SUB_OO_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R

    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 - RHS%E12
    RES%E13 = LHS%E13 - RHS%E13
    RES%E23 = LHS%E23 - RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 - RHS%E123

  END FUNCTION MDNUM3_SUB_OO_MS

  FUNCTION MDNUM3_SUB_RO_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R

    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3

    ! Order 2
    RES%E12 =  - RHS%E12
    RES%E13 =  - RHS%E13
    RES%E23 =  - RHS%E23

    ! Order 3
    RES%E123 =  - RHS%E123

  END FUNCTION MDNUM3_SUB_RO_MS

  FUNCTION MDNUM3_SUB_OR_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_SUB_OR_MS

  FUNCTION MDNUM3_MUL_OO_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    !  Multiplication like function 'LHS*RHS'

    ! Order 0
    RES%R = LHS%R*RHS%R

    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R

    ! Order 2
    RES%E12 = LHS%R*RHS%E12 + LHS%E12*RHS%R + LHS%E1*RHS%E2 &
            + LHS%E2*RHS%E1
    RES%E13 = LHS%R*RHS%E13 + LHS%E13*RHS%R + LHS%E1*RHS%E3 &
            + LHS%E3*RHS%E1
    RES%E23 = LHS%R*RHS%E23 + LHS%E23*RHS%R + LHS%E2*RHS%E3 &
            + LHS%E3*RHS%E2

    ! Order 3
    RES%E123 = LHS%R*RHS%E123 + LHS%E123*RHS%R + LHS%E1*RHS%E23 &
             + LHS%E23*RHS%E1 + LHS%E2*RHS%E13 + LHS%E13*RHS%E2 &
             + LHS%E3*RHS%E12 + LHS%E12*RHS%E3

  END FUNCTION MDNUM3_MUL_OO_MS

  FUNCTION MDNUM3_MUL_RO_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R

    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3

    ! Order 2
    RES%E12 = LHS*RHS%E12
    RES%E13 = LHS*RHS%E13
    RES%E23 = LHS*RHS%E23

    ! Order 3
    RES%E123 = LHS*RHS%E123

  END FUNCTION MDNUM3_MUL_RO_MS

  FUNCTION MDNUM3_MUL_OR_MS(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    REAL(DP), INTENT(IN) :: RHS
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(LHS,2)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS

    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS

    ! Order 2
    RES%E12 = LHS%E12*RHS
    RES%E13 = LHS%E13*RHS
    RES%E23 = LHS%E23*RHS

    ! Order 3
    RES%E123 = LHS%E123*RHS

  END FUNCTION MDNUM3_MUL_OR_MS

  FUNCTION MDNUM3_ADD_OO_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R

    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 + RHS%E12
    RES%E13 = LHS%E13 + RHS%E13
    RES%E23 = LHS%E23 + RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 + RHS%E123

  END FUNCTION MDNUM3_ADD_OO_SV

  FUNCTION MDNUM3_ADD_RO_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R

    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3

    ! Order 2
    RES%E12 =  + RHS%E12
    RES%E13 =  + RHS%E13
    RES%E23 =  + RHS%E23

    ! Order 3
    RES%E123 =  + RHS%E123

  END FUNCTION MDNUM3_ADD_RO_SV

  FUNCTION MDNUM3_ADD_OR_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_ADD_OR_SV

  FUNCTION MDNUM3_SUB_OO_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R

    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 - RHS%E12
    RES%E13 = LHS%E13 - RHS%E13
    RES%E23 = LHS%E23 - RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 - RHS%E123

  END FUNCTION MDNUM3_SUB_OO_SV

  FUNCTION MDNUM3_SUB_RO_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R

    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3

    ! Order 2
    RES%E12 =  - RHS%E12
    RES%E13 =  - RHS%E13
    RES%E23 =  - RHS%E23

    ! Order 3
    RES%E123 =  - RHS%E123

  END FUNCTION MDNUM3_SUB_RO_SV

  FUNCTION MDNUM3_SUB_OR_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_SUB_OR_SV

  FUNCTION MDNUM3_MUL_OO_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    !  Multiplication like function 'LHS*RHS'

    ! Order 0
    RES%R = LHS%R*RHS%R

    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R

    ! Order 2
    RES%E12 = LHS%R*RHS%E12 + LHS%E12*RHS%R + LHS%E1*RHS%E2 &
            + LHS%E2*RHS%E1
    RES%E13 = LHS%R*RHS%E13 + LHS%E13*RHS%R + LHS%E1*RHS%E3 &
            + LHS%E3*RHS%E1
    RES%E23 = LHS%R*RHS%E23 + LHS%E23*RHS%R + LHS%E2*RHS%E3 &
            + LHS%E3*RHS%E2

    ! Order 3
    RES%E123 = LHS%R*RHS%E123 + LHS%E123*RHS%R + LHS%E1*RHS%E23 &
             + LHS%E23*RHS%E1 + LHS%E2*RHS%E13 + LHS%E13*RHS%E2 &
             + LHS%E3*RHS%E12 + LHS%E12*RHS%E3

  END FUNCTION MDNUM3_MUL_OO_SV

  FUNCTION MDNUM3_MUL_RO_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R

    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3

    ! Order 2
    RES%E12 = LHS*RHS%E12
    RES%E13 = LHS*RHS%E13
    RES%E23 = LHS*RHS%E23

    ! Order 3
    RES%E123 = LHS*RHS%E123

  END FUNCTION MDNUM3_MUL_RO_SV

  FUNCTION MDNUM3_MUL_OR_SV(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS(:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS

    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS

    ! Order 2
    RES%E12 = LHS%E12*RHS
    RES%E13 = LHS%E13*RHS
    RES%E23 = LHS%E23*RHS

    ! Order 3
    RES%E123 = LHS%E123*RHS

  END FUNCTION MDNUM3_MUL_OR_SV

  FUNCTION MDNUM3_ADD_OO_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R

    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 + RHS%E12
    RES%E13 = LHS%E13 + RHS%E13
    RES%E23 = LHS%E23 + RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 + RHS%E123

  END FUNCTION MDNUM3_ADD_OO_SM

  FUNCTION MDNUM3_ADD_RO_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R

    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3

    ! Order 2
    RES%E12 =  + RHS%E12
    RES%E13 =  + RHS%E13
    RES%E23 =  + RHS%E23

    ! Order 3
    RES%E123 =  + RHS%E123

  END FUNCTION MDNUM3_ADD_RO_SM

  FUNCTION MDNUM3_ADD_OR_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_ADD_OR_SM

  FUNCTION MDNUM3_SUB_OO_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R

    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3

    ! Order 2
    RES%E12 = LHS%E12 - RHS%E12
    RES%E13 = LHS%E13 - RHS%E13
    RES%E23 = LHS%E23 - RHS%E23

    ! Order 3
    RES%E123 = LHS%E123 - RHS%E123

  END FUNCTION MDNUM3_SUB_OO_SM

  FUNCTION MDNUM3_SUB_RO_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R

    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3

    ! Order 2
    RES%E12 =  - RHS%E12
    RES%E13 =  - RHS%E13
    RES%E23 =  - RHS%E23

    ! Order 3
    RES%E123 =  - RHS%E123

  END FUNCTION MDNUM3_SUB_RO_SM

  FUNCTION MDNUM3_SUB_OR_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS

    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3

    ! Order 2
    RES%E12 = LHS%E12
    RES%E13 = LHS%E13
    RES%E23 = LHS%E23

    ! Order 3
    RES%E123 = LHS%E123

  END FUNCTION MDNUM3_SUB_OR_SM

  FUNCTION MDNUM3_MUL_OO_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    !  Multiplication like function 'LHS*RHS'

    ! Order 0
    RES%R = LHS%R*RHS%R

    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R

    ! Order 2
    RES%E12 = LHS%R*RHS%E12 + LHS%E12*RHS%R + LHS%E1*RHS%E2 &
            + LHS%E2*RHS%E1
    RES%E13 = LHS%R*RHS%E13 + LHS%E13*RHS%R + LHS%E1*RHS%E3 &
            + LHS%E3*RHS%E1
    RES%E23 = LHS%R*RHS%E23 + LHS%E23*RHS%R + LHS%E2*RHS%E3 &
            + LHS%E3*RHS%E2

    ! Order 3
    RES%E123 = LHS%R*RHS%E123 + LHS%E123*RHS%R + LHS%E1*RHS%E23 &
             + LHS%E23*RHS%E1 + LHS%E2*RHS%E13 + LHS%E13*RHS%E2 &
             + LHS%E3*RHS%E12 + LHS%E12*RHS%E3

  END FUNCTION MDNUM3_MUL_OO_SM

  FUNCTION MDNUM3_MUL_RO_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R

    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3

    ! Order 2
    RES%E12 = LHS*RHS%E12
    RES%E13 = LHS*RHS%E13
    RES%E23 = LHS*RHS%E23

    ! Order 3
    RES%E123 = LHS*RHS%E123

  END FUNCTION MDNUM3_MUL_RO_SM

  FUNCTION MDNUM3_MUL_OR_SM(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS
    REAL(DP), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(RHS,1),SIZE(RHS,2)) 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS

    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS

    ! Order 2
    RES%E12 = LHS%E12*RHS
    RES%E13 = LHS%E13*RHS
    RES%E23 = LHS%E23*RHS

    ! Order 3
    RES%E123 = LHS%E123*RHS

  END FUNCTION MDNUM3_MUL_OR_SM

ELEMENTAL   FUNCTION MDNUM3_GEM_OOO(A,B,C)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: A 
    TYPE(MDNUM3), INTENT(IN) :: B 
    TYPE(MDNUM3), INTENT(IN) :: C 
    TYPE(MDNUM3) :: RES 

    !  General multiplication like function 'A*B + C'

    ! Order 0
    RES%R = C%R + A%R*B%R

    ! Order 1
    RES%E1 = C%E1 + A%R*B%E1 + A%E1*B%R
    RES%E2 = C%E2 + A%R*B%E2 + A%E2*B%R
    RES%E3 = C%E3 + A%R*B%E3 + A%E3*B%R

    ! Order 2
    RES%E12 = C%E12 + A%R*B%E12 + A%E12*B%R + A%E1*B%E2 &
            + A%E2*B%E1
    RES%E13 = C%E13 + A%R*B%E13 + A%E13*B%R + A%E1*B%E3 &
            + A%E3*B%E1
    RES%E23 = C%E23 + A%R*B%E23 + A%E23*B%R + A%E2*B%E3 &
            + A%E3*B%E2

    ! Order 3
    RES%E123 = C%E123 + A%R*B%E123 + A%E123*B%R + A%E1*B%E23 &
             + A%E23*B%E1 + A%E2*B%E13 + A%E13*B%E2 &
             + A%E3*B%E12 + A%E12*B%E3

  END FUNCTION MDNUM3_GEM_OOO

ELEMENTAL   FUNCTION MDNUM3_GEM_ROO(A,B,C)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: A 
    TYPE(MDNUM3), INTENT(IN) :: B 
    TYPE(MDNUM3), INTENT(IN) :: C 
    TYPE(MDNUM3) :: RES 

    !  General multiplication like function 'A*B + C'

    ! Order 0
    RES%R = C%R + A*B%R

    ! Order 1
    RES%E1 = C%E1 + A*B%E1
    RES%E2 = C%E2 + A*B%E2
    RES%E3 = C%E3 + A*B%E3

    ! Order 2
    RES%E12 = C%E12 + A*B%E12
    RES%E13 = C%E13 + A*B%E13
    RES%E23 = C%E23 + A*B%E23

    ! Order 3
    RES%E123 = C%E123 + A*B%E123

  END FUNCTION MDNUM3_GEM_ROO

ELEMENTAL   FUNCTION MDNUM3_GEM_ORO(A,B,C)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: A 
    REAL(DP), INTENT(IN) :: B 
    TYPE(MDNUM3), INTENT(IN) :: C 
    TYPE(MDNUM3) :: RES 

    !  General multiplication like function 'A*B + C'

    ! Order 0
    RES%R = C%R + A%R*B

    ! Order 1
    RES%E1 = C%E1 + A%E1*B
    RES%E2 = C%E2 + A%E2*B
    RES%E3 = C%E3 + A%E3*B

    ! Order 2
    RES%E12 = C%E12 + A%E12*B
    RES%E13 = C%E13 + A%E13*B
    RES%E23 = C%E23 + A%E23*B

    ! Order 3
    RES%E123 = C%E123 + A%E123*B

  END FUNCTION MDNUM3_GEM_ORO

  FUNCTION MDNUM3_FEVAL(X,DERIVS)&
    RESULT(RES)
    IMPLICIT NONE
    !  Definitions
    REAL(DP) :: FACTOR, COEF
    TYPE(MDNUM3), INTENT(IN)  :: X
    REAL(DP), INTENT(IN)  :: DERIVS(4)
    TYPE(MDNUM3) :: RES
    TYPE(MDNUM3) :: DX, DX_P

    FACTOR = 1.0_DP
    COEF   = 0.0_DP
    DX     = X
    DX_P   = X

    !  Set real part of deltas zero.
    DX%R = 0.0_DP
    DX_P%R = 0.0_DP

    ! Sets real part
    RES = DERIVS(1)

    ! Sets order 1
    FACTOR = FACTOR * 1
    COEF = DERIVS(2) / FACTOR
    RES = GEM(COEF,DX_P,RES)
    DX_P = DX_P*DX
    
    ! Sets order 2
    FACTOR = FACTOR * 2
    COEF = DERIVS(3) / FACTOR
    RES = GEM(COEF,DX_P,RES)
    DX_P = DX_P*DX
    
    ! Sets order 3
    FACTOR = FACTOR * 3
    COEF = DERIVS(4) / FACTOR
    RES = GEM(COEF,DX_P,RES)
    
  END FUNCTION MDNUM3_FEVAL

  FUNCTION MDNUM3_MATMUL_MDNUM3(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    !  Multiplication like function 'MATMUL(LHS,RHS)'

    ! Order 0
    RES%R = MATMUL(LHS%R,RHS%R)

    ! Order 1
    RES%E1 = MATMUL(LHS%R,RHS%E1) + MATMUL(LHS%E1,RHS%R)
    RES%E2 = MATMUL(LHS%R,RHS%E2) + MATMUL(LHS%E2,RHS%R)
    RES%E3 = MATMUL(LHS%R,RHS%E3) + MATMUL(LHS%E3,RHS%R)

    ! Order 2
    RES%E12 = MATMUL(LHS%R,RHS%E12) + MATMUL(LHS%E12,RHS%R) + MATMUL(LHS%E1,RHS%E2) &
            + MATMUL(LHS%E2,RHS%E1)
    RES%E13 = MATMUL(LHS%R,RHS%E13) + MATMUL(LHS%E13,RHS%R) + MATMUL(LHS%E1,RHS%E3) &
            + MATMUL(LHS%E3,RHS%E1)
    RES%E23 = MATMUL(LHS%R,RHS%E23) + MATMUL(LHS%E23,RHS%R) + MATMUL(LHS%E2,RHS%E3) &
            + MATMUL(LHS%E3,RHS%E2)

    ! Order 3
    RES%E123 = MATMUL(LHS%R,RHS%E123) + MATMUL(LHS%E123,RHS%R) + MATMUL(LHS%E1,RHS%E23) &
             + MATMUL(LHS%E23,RHS%E1) + MATMUL(LHS%E2,RHS%E13) + MATMUL(LHS%E13,RHS%E2) &
             + MATMUL(LHS%E3,RHS%E12) + MATMUL(LHS%E12,RHS%E3)

  END FUNCTION MDNUM3_MATMUL_MDNUM3

  FUNCTION R_MATMUL_MDNUM3(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS,RHS%R)

    ! Order 1
    RES%E1 = MATMUL(LHS,RHS%E1)
    RES%E2 = MATMUL(LHS,RHS%E2)
    RES%E3 = MATMUL(LHS,RHS%E3)

    ! Order 2
    RES%E12 = MATMUL(LHS,RHS%E12)
    RES%E13 = MATMUL(LHS,RHS%E13)
    RES%E23 = MATMUL(LHS,RHS%E23)

    ! Order 3
    RES%E123 = MATMUL(LHS,RHS%E123)

  END FUNCTION R_MATMUL_MDNUM3

  FUNCTION MDNUM3_MATMUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    REAL(DP), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUM3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS%R,RHS)

    ! Order 1
    RES%E1 = MATMUL(LHS%E1,RHS)
    RES%E2 = MATMUL(LHS%E2,RHS)
    RES%E3 = MATMUL(LHS%E3,RHS)

    ! Order 2
    RES%E12 = MATMUL(LHS%E12,RHS)
    RES%E13 = MATMUL(LHS%E13,RHS)
    RES%E23 = MATMUL(LHS%E23,RHS)

    ! Order 3
    RES%E123 = MATMUL(LHS%E123,RHS)

  END FUNCTION MDNUM3_MATMUL_R

  FUNCTION MDNUM3_TRANSPOSE(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUM3) :: RES (SIZE(LHS,2),SIZE(LHS,1))

    ! Negation like function 'TRANSPOSE(LHS)'
    ! Real
    RES%R = TRANSPOSE(LHS%R)
    ! Order 1
    RES%E1 = TRANSPOSE(LHS%E1)
    RES%E2 = TRANSPOSE(LHS%E2)
    RES%E3 = TRANSPOSE(LHS%E3)
    ! Order 2
    RES%E12 = TRANSPOSE(LHS%E12)
    RES%E13 = TRANSPOSE(LHS%E13)
    RES%E23 = TRANSPOSE(LHS%E23)
    ! Order 3
    RES%E123 = TRANSPOSE(LHS%E123)

  END FUNCTION MDNUM3_TRANSPOSE

FUNCTION MDNUM3_TO_CR_MAT_S(VAL) RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: VAL
    REAL(DP) :: RES(NUM_IM_DIR,NUM_IM_DIR) 
    INTEGER :: NCOLS=1, NROWS=1


    ! R x R -> R (1, 1)
    RES(1+NROWS*0:NROWS*1,1+NCOLS*0:NCOLS*1) = VAL%R
    ! R x E1 -> E1 (2, 2)
    RES(1+NROWS*1:NROWS*2,1+NCOLS*1:NCOLS*2) = VAL%R
    ! E1 x R -> E1 (2, 1)
    RES(1+NROWS*1:NROWS*2,1+NCOLS*0:NCOLS*1) = VAL%E1
    ! R x E2 -> E2 (3, 3)
    RES(1+NROWS*2:NROWS*3,1+NCOLS*2:NCOLS*3) = VAL%R
    ! E2 x R -> E2 (3, 1)
    RES(1+NROWS*2:NROWS*3,1+NCOLS*0:NCOLS*1) = VAL%E2
    ! R x E3 -> E3 (4, 4)
    RES(1+NROWS*3:NROWS*4,1+NCOLS*3:NCOLS*4) = VAL%R
    ! E3 x R -> E3 (4, 1)
    RES(1+NROWS*3:NROWS*4,1+NCOLS*0:NCOLS*1) = VAL%E3
    ! R x E12 -> E12 (5, 5)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*4:NCOLS*5) = VAL%R
    ! E12 x R -> E12 (5, 1)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*0:NCOLS*1) = VAL%E12
    ! E1 x E2 -> E12 (5, 3)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*2:NCOLS*3) = VAL%E1
    ! E2 x E1 -> E12 (5, 2)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*1:NCOLS*2) = VAL%E2
    ! R x E13 -> E13 (6, 6)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*5:NCOLS*6) = VAL%R
    ! E13 x R -> E13 (6, 1)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*0:NCOLS*1) = VAL%E13
    ! E1 x E3 -> E13 (6, 4)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*3:NCOLS*4) = VAL%E1
    ! E3 x E1 -> E13 (6, 2)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*1:NCOLS*2) = VAL%E3
    ! R x E23 -> E23 (7, 7)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*6:NCOLS*7) = VAL%R
    ! E23 x R -> E23 (7, 1)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*0:NCOLS*1) = VAL%E23
    ! E2 x E3 -> E23 (7, 4)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*3:NCOLS*4) = VAL%E2
    ! E3 x E2 -> E23 (7, 3)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*2:NCOLS*3) = VAL%E3
    ! R x E123 -> E123 (8, 8)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*7:NCOLS*8) = VAL%R
    ! E123 x R -> E123 (8, 1)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*0:NCOLS*1) = VAL%E123
    ! E1 x E23 -> E123 (8, 7)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*6:NCOLS*7) = VAL%E1
    ! E23 x E1 -> E123 (8, 2)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*1:NCOLS*2) = VAL%E23
    ! E2 x E13 -> E123 (8, 6)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*5:NCOLS*6) = VAL%E2
    ! E13 x E2 -> E123 (8, 3)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*2:NCOLS*3) = VAL%E13
    ! E3 x E12 -> E123 (8, 5)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*4:NCOLS*5) = VAL%E3
    ! E12 x E3 -> E123 (8, 4)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*3:NCOLS*4) = VAL%E12
  END FUNCTION MDNUM3_TO_CR_MAT_S

FUNCTION MDNUM3_TO_CR_MAT_V(VAL) RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: VAL(:)
    REAL(DP) :: RES(NUM_IM_DIR*SIZE(VAL,1),NUM_IM_DIR) 
    INTEGER :: NCOLS=1, NROWS=1

    NROWS = SIZE(VAL,1)

    ! R x R -> R (1, 1)
    RES(1+NROWS*0:NROWS*1,1) = VAL%R
    ! R x E1 -> E1 (2, 2)
    RES(1+NROWS*1:NROWS*2,2) = VAL%R
    ! E1 x R -> E1 (2, 1)
    RES(1+NROWS*1:NROWS*2,1) = VAL%E1
    ! R x E2 -> E2 (3, 3)
    RES(1+NROWS*2:NROWS*3,3) = VAL%R
    ! E2 x R -> E2 (3, 1)
    RES(1+NROWS*2:NROWS*3,1) = VAL%E2
    ! R x E3 -> E3 (4, 4)
    RES(1+NROWS*3:NROWS*4,4) = VAL%R
    ! E3 x R -> E3 (4, 1)
    RES(1+NROWS*3:NROWS*4,1) = VAL%E3
    ! R x E12 -> E12 (5, 5)
    RES(1+NROWS*4:NROWS*5,5) = VAL%R
    ! E12 x R -> E12 (5, 1)
    RES(1+NROWS*4:NROWS*5,1) = VAL%E12
    ! E1 x E2 -> E12 (5, 3)
    RES(1+NROWS*4:NROWS*5,3) = VAL%E1
    ! E2 x E1 -> E12 (5, 2)
    RES(1+NROWS*4:NROWS*5,2) = VAL%E2
    ! R x E13 -> E13 (6, 6)
    RES(1+NROWS*5:NROWS*6,6) = VAL%R
    ! E13 x R -> E13 (6, 1)
    RES(1+NROWS*5:NROWS*6,1) = VAL%E13
    ! E1 x E3 -> E13 (6, 4)
    RES(1+NROWS*5:NROWS*6,4) = VAL%E1
    ! E3 x E1 -> E13 (6, 2)
    RES(1+NROWS*5:NROWS*6,2) = VAL%E3
    ! R x E23 -> E23 (7, 7)
    RES(1+NROWS*6:NROWS*7,7) = VAL%R
    ! E23 x R -> E23 (7, 1)
    RES(1+NROWS*6:NROWS*7,1) = VAL%E23
    ! E2 x E3 -> E23 (7, 4)
    RES(1+NROWS*6:NROWS*7,4) = VAL%E2
    ! E3 x E2 -> E23 (7, 3)
    RES(1+NROWS*6:NROWS*7,3) = VAL%E3
    ! R x E123 -> E123 (8, 8)
    RES(1+NROWS*7:NROWS*8,8) = VAL%R
    ! E123 x R -> E123 (8, 1)
    RES(1+NROWS*7:NROWS*8,1) = VAL%E123
    ! E1 x E23 -> E123 (8, 7)
    RES(1+NROWS*7:NROWS*8,7) = VAL%E1
    ! E23 x E1 -> E123 (8, 2)
    RES(1+NROWS*7:NROWS*8,2) = VAL%E23
    ! E2 x E13 -> E123 (8, 6)
    RES(1+NROWS*7:NROWS*8,6) = VAL%E2
    ! E13 x E2 -> E123 (8, 3)
    RES(1+NROWS*7:NROWS*8,3) = VAL%E13
    ! E3 x E12 -> E123 (8, 5)
    RES(1+NROWS*7:NROWS*8,5) = VAL%E3
    ! E12 x E3 -> E123 (8, 4)
    RES(1+NROWS*7:NROWS*8,4) = VAL%E12
  END FUNCTION MDNUM3_TO_CR_MAT_V

FUNCTION MDNUM3_TO_CR_MAT_M(VAL) RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUM3), INTENT(IN) :: VAL(:,:)
    REAL(DP) :: RES(NUM_IM_DIR*SIZE(VAL,1),NUM_IM_DIR*SIZE(VAL,2)) 
    INTEGER :: NCOLS=1, NROWS=1

    NCOLS = SIZE(VAL,1)
    NROWS = SIZE(VAL,2)

    ! R x R -> R (1, 1)
    RES(1+NROWS*0:NROWS*1,1+NCOLS*0:NCOLS*1) = VAL%R
    ! R x E1 -> E1 (2, 2)
    RES(1+NROWS*1:NROWS*2,1+NCOLS*1:NCOLS*2) = VAL%R
    ! E1 x R -> E1 (2, 1)
    RES(1+NROWS*1:NROWS*2,1+NCOLS*0:NCOLS*1) = VAL%E1
    ! R x E2 -> E2 (3, 3)
    RES(1+NROWS*2:NROWS*3,1+NCOLS*2:NCOLS*3) = VAL%R
    ! E2 x R -> E2 (3, 1)
    RES(1+NROWS*2:NROWS*3,1+NCOLS*0:NCOLS*1) = VAL%E2
    ! R x E3 -> E3 (4, 4)
    RES(1+NROWS*3:NROWS*4,1+NCOLS*3:NCOLS*4) = VAL%R
    ! E3 x R -> E3 (4, 1)
    RES(1+NROWS*3:NROWS*4,1+NCOLS*0:NCOLS*1) = VAL%E3
    ! R x E12 -> E12 (5, 5)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*4:NCOLS*5) = VAL%R
    ! E12 x R -> E12 (5, 1)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*0:NCOLS*1) = VAL%E12
    ! E1 x E2 -> E12 (5, 3)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*2:NCOLS*3) = VAL%E1
    ! E2 x E1 -> E12 (5, 2)
    RES(1+NROWS*4:NROWS*5,1+NCOLS*1:NCOLS*2) = VAL%E2
    ! R x E13 -> E13 (6, 6)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*5:NCOLS*6) = VAL%R
    ! E13 x R -> E13 (6, 1)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*0:NCOLS*1) = VAL%E13
    ! E1 x E3 -> E13 (6, 4)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*3:NCOLS*4) = VAL%E1
    ! E3 x E1 -> E13 (6, 2)
    RES(1+NROWS*5:NROWS*6,1+NCOLS*1:NCOLS*2) = VAL%E3
    ! R x E23 -> E23 (7, 7)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*6:NCOLS*7) = VAL%R
    ! E23 x R -> E23 (7, 1)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*0:NCOLS*1) = VAL%E23
    ! E2 x E3 -> E23 (7, 4)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*3:NCOLS*4) = VAL%E2
    ! E3 x E2 -> E23 (7, 3)
    RES(1+NROWS*6:NROWS*7,1+NCOLS*2:NCOLS*3) = VAL%E3
    ! R x E123 -> E123 (8, 8)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*7:NCOLS*8) = VAL%R
    ! E123 x R -> E123 (8, 1)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*0:NCOLS*1) = VAL%E123
    ! E1 x E23 -> E123 (8, 7)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*6:NCOLS*7) = VAL%E1
    ! E23 x E1 -> E123 (8, 2)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*1:NCOLS*2) = VAL%E23
    ! E2 x E13 -> E123 (8, 6)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*5:NCOLS*6) = VAL%E2
    ! E13 x E2 -> E123 (8, 3)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*2:NCOLS*3) = VAL%E13
    ! E3 x E12 -> E123 (8, 5)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*4:NCOLS*5) = VAL%E3
    ! E12 x E3 -> E123 (8, 4)
    RES(1+NROWS*7:NROWS*8,1+NCOLS*3:NCOLS*4) = VAL%E12
  END FUNCTION MDNUM3_TO_CR_MAT_M

  PURE FUNCTION DER_R_COS( X ) RESULT(DERIVS)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER+1)
      REAL(DP), INTENT(IN) :: X
      INTEGER :: I
      INTEGER :: S
      INTEGER :: SIGN
      
      SIGN = 1
      S = 0

      DO I = 1,TORDER+1
      
          IF (S == 0) THEN
              DERIVS(I) = SIGN * COS(X)
          ELSE
              SIGN = SIGN * (-1);
              DERIVS(I) = SIGN * SIN(X)
          END IF 
      
          S = MOD((S+1),2)
       
      END DO

  END FUNCTION DER_R_COS

  PURE FUNCTION DER_R_SIN( X ) RESULT(DERIVS)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER+1)
      REAL(DP), INTENT(IN) :: X
      INTEGER :: I
      INTEGER :: S 
      INTEGER :: SIGN 
      
      SIGN = -1
      S = 1
      DO I = 1,TORDER+1
      
          IF (S == 0) THEN
              DERIVS(I) = SIGN * COS(X)
          ELSE
              SIGN = SIGN * (-1)
              DERIVS(I) = SIGN * SIN(X)
          END IF 
      
          S = MOD((S+1),2)
       
      END DO

  END FUNCTION DER_R_SIN

  PURE FUNCTION DER_R_LOG( X ) RESULT (DERIVS)
      IMPLICIT NONE  
      REAL(DP) :: DERIVS(TORDER+1)
      REAL(DP), INTENT(IN) :: X

      INTEGER :: SIGN 
      REAL(DP):: FACTOR 
      INTEGER :: I    

      SIGN = -1
      FACTOR = 1.0_DP

      DERIVS(1) = LOG(X)

      DO I = 2,TORDER +1
                   
          DERIVS(I) = FACTOR * SIGN**(I+1) / (X**I)
          FACTOR    = FACTOR * I
          
      END DO

  END FUNCTION DER_R_LOG

  PURE FUNCTION DER_R_EXP( X ) RESULT (DERIVS)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER+1)
      REAL(DP), INTENT(IN) :: X
      REAL(DP) :: VAL 
      INTEGER I

      VAL = EXP(X)

      DO I=1,TORDER+1
          DERIVS(I) = VAL
      END DO

  END FUNCTION DER_R_EXP

  PURE FUNCTION DER_R_POW( X, E ) RESULT (DERIVS)
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: X ! Value
      REAL(DP), INTENT(IN) :: E ! Exponent
      REAL(DP) :: DERIVS(TORDER+1)
      REAL(DP) :: POWER_I 
      REAL(DP) :: X0 
      INTEGER  :: FLAG 
      REAL(DP) :: FACTOR
      INTEGER  ::  I
      
      POWER_I = E
      X0 = X
      FLAG = 0
      FACTOR = 1.0_DP

      DO I=1, TORDER+1
          IF( POWER_I /= 0.0_DP) THEN
              DERIVS(I) = FACTOR * ( X0 ** POWER_I )
              FACTOR = FACTOR*POWER_I
              POWER_I = POWER_I - 1
          ELSE
              IF (FLAG == 0 ) THEN
                  DERIVS(I) = FACTOR
                  FLAG = 1
              ELSE
                  DERIVS(I) = 0.0_DP
              END IF 
          END IF 
      END DO
  END FUNCTION DER_R_POW

  FUNCTION MDNUM3_SIN(X) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      TYPE(MDNUM3), INTENT(IN) :: X
      TYPE(MDNUM3) :: RES

      DERIVS = DER_R_SIN( X%R )

      RES = FEVAL(X,DERIVS)

  END FUNCTION MDNUM3_SIN

  FUNCTION MDNUM3_COS(X) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      TYPE(MDNUM3), INTENT(IN) :: X
      TYPE(MDNUM3) :: RES

      DERIVS = DER_R_COS( X%R )

      RES = FEVAL(X,DERIVS)

  END FUNCTION MDNUM3_COS

  FUNCTION MDNUM3_LOG(X) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      TYPE(MDNUM3), INTENT(IN) :: X
      TYPE(MDNUM3) :: RES

      DERIVS = DER_R_LOG( X%R )

      RES = FEVAL(X,DERIVS)

  END FUNCTION MDNUM3_LOG

  FUNCTION MDNUM3_EXP(X) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      TYPE(MDNUM3), INTENT(IN) :: X
      TYPE(MDNUM3) :: RES

      DERIVS = DER_R_EXP( X%R )

      RES = FEVAL(X,DERIVS)

  END FUNCTION MDNUM3_EXP

  FUNCTION MDNUM3_SQRT(X) RESULT(RES)
      IMPLICIT NONE
      TYPE(MDNUM3), INTENT(IN) :: X
      TYPE(MDNUM3) :: RES

      RES = X**0.5_DP

  END FUNCTION MDNUM3_SQRT

  FUNCTION MDNUM3_POW(X,E) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      TYPE(MDNUM3), INTENT(IN) :: X
      REAL(DP), INTENT(IN) :: E
      TYPE(MDNUM3) :: RES

      DERIVS = DER_R_POW( X%R, E )

      RES = FEVAL(X,DERIVS)

  END FUNCTION MDNUM3_POW

  FUNCTION MDNUM3_DIVISION_OO(X,Y) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      TYPE(MDNUM3), INTENT(IN) :: X
      TYPE(MDNUM3), INTENT(IN) :: Y
      TYPE(MDNUM3) :: RES

      RES = X*(Y**(-1.d0))

  END FUNCTION MDNUM3_DIVISION_OO

  FUNCTION MDNUM3_DIVISION_OR(X,Y) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      TYPE(MDNUM3), INTENT(IN) :: X
      REAL(DP), INTENT(IN) :: Y
      TYPE(MDNUM3) :: RES

      RES = X*(Y**(-1.d0))

  END FUNCTION MDNUM3_DIVISION_OR

  FUNCTION MDNUM3_DIVISION_RO(X,Y) RESULT(RES)
      IMPLICIT NONE
      REAL(DP) :: DERIVS(TORDER + 1) 
      REAL(DP), INTENT(IN) :: X
      TYPE(MDNUM3), INTENT(IN) :: Y
      TYPE(MDNUM3) :: RES

      RES = X*(Y**(-1.d0))

  END FUNCTION MDNUM3_DIVISION_RO

  ELEMENTAL FUNCTION MDNUM3_REAL(X) RESULT(RES)
      IMPLICIT NONE
      TYPE(MDNUM3), INTENT(IN) :: X
      REAL(DP) :: RES

      RES = X%R

  END FUNCTION MDNUM3_REAL

  SUBROUTINE MDNUM3_PPRINT_M_R(X, FMT)
      IMPLICIT NONE
      REAL(DP), INTENT(IN) :: X(:,:)
      INTEGER :: I, J
      CHARACTER(*), INTENT(IN), OPTIONAL :: FMT
      CHARACTER(:),ALLOCATABLE :: out_fmt
      
      IF (PRESENT(fmt)) THEN
        out_fmt = trim(fmt)
      ELSE
        out_fmt = 'F8.3'
      END IF
      
      write(*,'(A)',advance='no') "["
      
      DO I=1,SIZE(X,1)
        
        IF (I == 1) THEN
          write(*,'(A)',advance='no') "["
        ELSE
          write(*,'(A)',advance='no') " ["
        END IF 

        DO J=1,SIZE(X,2)
          
          write(*,'('//trim(out_fmt)//')',advance='no') X(I,J)

        END DO
        
        write(*,'(A)') "]"
      
      END DO

      write(*,'(A)') "]"
      

  END SUBROUTINE MDNUM3_PPRINT_M_R
END MODULE MDUAL3
