MODULE MDUALM2N2

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP         = 8
  INTEGER, PARAMETER :: NUM_IM_DIR = 4
  INTEGER, PARAMETER :: TORDER     = 2

  TYPE MDNUMM2N2
    ! Real
    REAL(DP) :: R
    ! Order 1
    REAL(DP) :: E1
    REAL(DP) :: E2
    ! Order 2
    REAL(DP) :: E12
  END TYPE MDNUMM2N2

  INTERFACE OPERATOR(*)
    MODULE PROCEDURE MDNUMM2N2_MUL_oo,MDNUMM2N2_MUL_Ro,MDNUMM2N2_MUL_oR
  END INTERFACE

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE MDNUMM2N2_ADD_oo,MDNUMM2N2_ADD_Ro,MDNUMM2N2_ADD_oR
  END INTERFACE

  INTERFACE OPERATOR(-)
    MODULE PROCEDURE MDNUMM2N2_NEG,MDNUMM2N2_SUB_oo,MDNUMM2N2_SUB_Ro,MDNUMM2N2_SUB_oR
  END INTERFACE

  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE MDNUMM2N2_ASSIGN_R
  END INTERFACE

  INTERFACE TRANSPOSE
    MODULE PROCEDURE MDNUMM2N2_TRANSPOSE
  END INTERFACE

  INTERFACE MATMUL
    MODULE PROCEDURE MDNUMM2N2_MATMUL_MDNUMM2N2,R_MATMUL_MDNUMM2N2,MDNUMM2N2_MATMUL_R
  END INTERFACE

  CONTAINS

  ELEMENTAL SUBROUTINE MDNUMM2N2_ASSIGN_R(RES,LHS)
    
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2), INTENT(OUT) :: RES 

    ! Assign like function 'LHS'
    ! Real
    RES%R = LHS
    ! Order 1
    RES%E1 = 0.0_dp
    RES%E2 = 0.0_dp
    ! Order 2
    RES%E12 = 0.0_dp

  END SUBROUTINE MDNUMM2N2_ASSIGN_R

  ELEMENTAL FUNCTION MDNUMM2N2_ADD_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R
    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    ! Order 2
    RES%E12 = LHS%E12 + RHS%E12

  END FUNCTION MDNUMM2N2_ADD_oo

  ELEMENTAL FUNCTION MDNUMM2N2_ADD_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R
    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    ! Order 2
    RES%E12 =  + RHS%E12

  END FUNCTION MDNUMM2N2_ADD_Ro

  ELEMENTAL FUNCTION MDNUMM2N2_ADD_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    ! Order 2
    RES%E12 = LHS%E12

  END FUNCTION MDNUMM2N2_ADD_oR

  ELEMENTAL FUNCTION MDNUMM2N2_NEG(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Negation like function '-LHS'
    ! Real
    RES%R = -LHS%R
    ! Order 1
    RES%E1 = -LHS%E1
    RES%E2 = -LHS%E2
    ! Order 2
    RES%E12 = -LHS%E12

  END FUNCTION MDNUMM2N2_NEG

  ELEMENTAL FUNCTION MDNUMM2N2_SUB_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R
    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    ! Order 2
    RES%E12 = LHS%E12 - RHS%E12

  END FUNCTION MDNUMM2N2_SUB_oo

  ELEMENTAL FUNCTION MDNUMM2N2_SUB_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R
    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    ! Order 2
    RES%E12 =  - RHS%E12

  END FUNCTION MDNUMM2N2_SUB_Ro

  ELEMENTAL FUNCTION MDNUMM2N2_SUB_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    ! Order 2
    RES%E12 = LHS%E12

  END FUNCTION MDNUMM2N2_SUB_oR

  ELEMENTAL FUNCTION MDNUMM2N2_MUL_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    !  Multiplication like function 'LHS*RHS'
    ! Order 0
    RES%R = LHS%R*RHS%R
    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    ! Order 2
    RES%E12 = LHS%R*RHS%E12 + LHS%E12*RHS%R + LHS%E1*RHS%E2 &
            + LHS%E2*RHS%E1

  END FUNCTION MDNUMM2N2_MUL_oo

  ELEMENTAL FUNCTION MDNUMM2N2_MUL_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R
    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    ! Order 2
    RES%E12 = LHS*RHS%E12

  END FUNCTION MDNUMM2N2_MUL_Ro

  ELEMENTAL FUNCTION MDNUMM2N2_MUL_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(MDNUMM2N2) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS
    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    ! Order 2
    RES%E12 = LHS%E12*RHS

  END FUNCTION MDNUMM2N2_MUL_oR

  FUNCTION MDNUMM2N2_MATMUL_MDNUMM2N2(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUMM2N2) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    !  Multiplication like function 'MATMUL(LHS,RHS)'
    ! Order 0
    RES%R = MATMUL(LHS%R,RHS%R)
    ! Order 1
    RES%E1 = MATMUL(LHS%R,RHS%E1) + MATMUL(LHS%E1,RHS%R)
    RES%E2 = MATMUL(LHS%R,RHS%E2) + MATMUL(LHS%E2,RHS%R)
    ! Order 2
    RES%E12 = MATMUL(LHS%R,RHS%E12) + MATMUL(LHS%E12,RHS%R) + MATMUL(LHS%E1,RHS%E2) &
            + MATMUL(LHS%E2,RHS%E1)

  END FUNCTION MDNUMM2N2_MATMUL_MDNUMM2N2

  FUNCTION R_MATMUL_MDNUMM2N2(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUMM2N2), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUMM2N2) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS,RHS%R)
    ! Order 1
    RES%E1 = MATMUL(LHS,RHS%E1)
    RES%E2 = MATMUL(LHS,RHS%E2)
    ! Order 2
    RES%E12 = MATMUL(LHS,RHS%E12)

  END FUNCTION R_MATMUL_MDNUMM2N2

  FUNCTION MDNUMM2N2_MATMUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS(:,:)
    REAL(DP), INTENT(IN) :: RHS(:,:)
    TYPE(MDNUMM2N2) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS%R,RHS)
    ! Order 1
    RES%E1 = MATMUL(LHS%E1,RHS)
    RES%E2 = MATMUL(LHS%E2,RHS)
    ! Order 2
    RES%E12 = MATMUL(LHS%E12,RHS)

  END FUNCTION MDNUMM2N2_MATMUL_R

  FUNCTION MDNUMM2N2_TRANSPOSE(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(MDNUMM2N2), INTENT(IN) :: LHS(:,:)
    TYPE(MDNUMM2N2) :: RES (SIZE(LHS,2),SIZE(LHS,1))

    ! Negation like function 'TRANSPOSE(LHS)'
    ! Real
    RES%R = TRANSPOSE(LHS%R)
    ! Order 1
    RES%E1 = TRANSPOSE(LHS%E1)
    RES%E2 = TRANSPOSE(LHS%E2)
    ! Order 2
    RES%E12 = TRANSPOSE(LHS%E12)

  END FUNCTION MDNUMM2N2_TRANSPOSE

END MODULE MDUALM2N2
