MODULE OTIM1N3

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP         = 8
  INTEGER, PARAMETER :: NUM_IM_DIR = 4
  INTEGER, PARAMETER :: TORDER     = 3

  TYPE ONUMM1N3
    ! Real
    REAL(DP) :: R
    ! Order 1
    REAL(DP) :: E1
    ! Order 2
    REAL(DP) :: E11
    ! Order 3
    REAL(DP) :: E111
  END TYPE ONUMM1N3

  INTERFACE OPERATOR(*)
    MODULE PROCEDURE ONUMM1N3_MUL_oo,ONUMM1N3_MUL_Ro,ONUMM1N3_MUL_oR
  END INTERFACE

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE ONUMM1N3_ADD_oo,ONUMM1N3_ADD_Ro,ONUMM1N3_ADD_oR
  END INTERFACE

  INTERFACE OPERATOR(-)
    MODULE PROCEDURE ONUMM1N3_NEG,ONUMM1N3_SUB_oo,ONUMM1N3_SUB_Ro,ONUMM1N3_SUB_oR
  END INTERFACE

  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE ONUMM1N3_ASSIGN_R
  END INTERFACE

  INTERFACE TRANSPOSE
    MODULE PROCEDURE ONUMM1N3_TRANSPOSE
  END INTERFACE

  INTERFACE MATMUL
    MODULE PROCEDURE ONUMM1N3_MATMUL_ONUMM1N3,R_MATMUL_ONUMM1N3,ONUMM1N3_MATMUL_R
  END INTERFACE

  CONTAINS

  ELEMENTAL SUBROUTINE ONUMM1N3_ASSIGN_R(RES,LHS)
    
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3), INTENT(OUT) :: RES 

    ! Assign like function 'LHS'
    ! Real
    RES%R = LHS
    ! Order 1
    RES%E1 = 0.0_dp
    ! Order 2
    RES%E11 = 0.0_dp
    ! Order 3
    RES%E111 = 0.0_dp

  END SUBROUTINE ONUMM1N3_ASSIGN_R

  ELEMENTAL FUNCTION ONUMM1N3_ADD_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Addition like function 'LHS + RHS'
    !  Real
    RES%R = LHS%R + RHS%R
    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    ! Order 2
    RES%E11 = LHS%E11 + RHS%E11
    ! Order 3
    RES%E111 = LHS%E111 + RHS%E111

  END FUNCTION ONUMM1N3_ADD_oo

  ELEMENTAL FUNCTION ONUMM1N3_ADD_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R
    ! Order 1
    RES%E1 =  + RHS%E1
    ! Order 2
    RES%E11 =  + RHS%E11
    ! Order 3
    RES%E111 =  + RHS%E111

  END FUNCTION ONUMM1N3_ADD_Ro

  ELEMENTAL FUNCTION ONUMM1N3_ADD_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS
    ! Order 1
    RES%E1 = LHS%E1
    ! Order 2
    RES%E11 = LHS%E11
    ! Order 3
    RES%E111 = LHS%E111

  END FUNCTION ONUMM1N3_ADD_oR

  ELEMENTAL FUNCTION ONUMM1N3_NEG(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3) :: RES 

    ! Negation like function '-LHS'
    ! Real
    RES%R = -LHS%R
    ! Order 1
    RES%E1 = -LHS%E1
    ! Order 2
    RES%E11 = -LHS%E11
    ! Order 3
    RES%E111 = -LHS%E111

  END FUNCTION ONUMM1N3_NEG

  ELEMENTAL FUNCTION ONUMM1N3_SUB_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Addition like function 'LHS - RHS'
    !  Real
    RES%R = LHS%R - RHS%R
    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    ! Order 2
    RES%E11 = LHS%E11 - RHS%E11
    ! Order 3
    RES%E111 = LHS%E111 - RHS%E111

  END FUNCTION ONUMM1N3_SUB_oo

  ELEMENTAL FUNCTION ONUMM1N3_SUB_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R
    ! Order 1
    RES%E1 =  - RHS%E1
    ! Order 2
    RES%E11 =  - RHS%E11
    ! Order 3
    RES%E111 =  - RHS%E111

  END FUNCTION ONUMM1N3_SUB_Ro

  ELEMENTAL FUNCTION ONUMM1N3_SUB_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS
    ! Order 1
    RES%E1 = LHS%E1
    ! Order 2
    RES%E11 = LHS%E11
    ! Order 3
    RES%E111 = LHS%E111

  END FUNCTION ONUMM1N3_SUB_oR

  ELEMENTAL FUNCTION ONUMM1N3_MUL_oo(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    !  Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS%R*RHS%R
    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    ! Order 2
    RES%E11 = LHS%R*RHS%E11 + LHS%E11*RHS%R + LHS%E1*RHS%E1
    ! Order 3
    RES%E111 = LHS%R*RHS%E111 + LHS%E111*RHS%R + LHS%E1*RHS%E11 &
             + LHS%E11*RHS%E1

  END FUNCTION ONUMM1N3_MUL_oo

  ELEMENTAL FUNCTION ONUMM1N3_MUL_Ro(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N3), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS*RHS%R
    ! Order 1
    RES%E1 = LHS*RHS%E1
    ! Order 2
    RES%E11 = LHS*RHS%E11
    ! Order 3
    RES%E111 = LHS*RHS%E111

  END FUNCTION ONUMM1N3_MUL_Ro

  ELEMENTAL FUNCTION ONUMM1N3_MUL_oR(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM1N3) :: RES 

    ! Multiplication like function 'LHS*RHS'
    !  Real
    RES%R = LHS%R*RHS
    ! Order 1
    RES%E1 = LHS%E1*RHS
    ! Order 2
    RES%E11 = LHS%E11*RHS
    ! Order 3
    RES%E111 = LHS%E111*RHS

  END FUNCTION ONUMM1N3_MUL_oR

  FUNCTION ONUMM1N3_MATMUL_ONUMM1N3(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS(:,:)
    TYPE(ONUMM1N3), INTENT(IN) :: RHS(:,:)
    TYPE(ONUMM1N3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    !  Multiplication like function 'MATMUL(LHS,RHS)'
    ! Real
    RES%R = MATMUL(LHS%R,RHS%R)
    ! Order 1
    RES%E1 = MATMUL(LHS%R,RHS%E1) + MATMUL(LHS%E1,RHS%R)
    ! Order 2
    RES%E11 = MATMUL(LHS%R,RHS%E11) + MATMUL(LHS%E11,RHS%R) + MATMUL(LHS%E1,RHS%E1)
    ! Order 3
    RES%E111 = MATMUL(LHS%R,RHS%E111) + MATMUL(LHS%E111,RHS%R) + MATMUL(LHS%E1,RHS%E11) &
             + MATMUL(LHS%E11,RHS%E1)

  END FUNCTION ONUMM1N3_MATMUL_ONUMM1N3

  FUNCTION R_MATMUL_ONUMM1N3(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:)
    TYPE(ONUMM1N3), INTENT(IN) :: RHS(:,:)
    TYPE(ONUMM1N3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS,RHS%R)
    ! Order 1
    RES%E1 = MATMUL(LHS,RHS%E1)
    ! Order 2
    RES%E11 = MATMUL(LHS,RHS%E11)
    ! Order 3
    RES%E111 = MATMUL(LHS,RHS%E111)

  END FUNCTION R_MATMUL_ONUMM1N3

  FUNCTION ONUMM1N3_MATMUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS(:,:)
    REAL(DP), INTENT(IN) :: RHS(:,:)
    TYPE(ONUMM1N3) :: RES(SIZE(LHS,1),SIZE(RHS,2))

    ! Multiplication like function 'MATMUL(LHS,RHS)'
    !  Real
    RES%R = MATMUL(LHS%R,RHS)
    ! Order 1
    RES%E1 = MATMUL(LHS%E1,RHS)
    ! Order 2
    RES%E11 = MATMUL(LHS%E11,RHS)
    ! Order 3
    RES%E111 = MATMUL(LHS%E111,RHS)

  END FUNCTION ONUMM1N3_MATMUL_R

  FUNCTION ONUMM1N3_TRANSPOSE(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N3), INTENT(IN) :: LHS(:,:)
    TYPE(ONUMM1N3) :: RES (SIZE(LHS,2),SIZE(LHS,1))

    ! Negation like function 'TRANSPOSE(LHS)'
    ! Real
    RES%R = TRANSPOSE(LHS%R)
    ! Order 1
    RES%E1 = TRANSPOSE(LHS%E1)
    ! Order 2
    RES%E11 = TRANSPOSE(LHS%E11)
    ! Order 3
    RES%E111 = TRANSPOSE(LHS%E111)

  END FUNCTION ONUMM1N3_TRANSPOSE

END MODULE OTIM1N3
