"""
Tests installation, importability of submodules, and precomputed data tables.
"""

import importlib
import os
import numpy as np
import pytest


def test_import_pyoti():
    """
    Test importing the top-level pyoti package.
    """
    import pyoti

    assert pyoti is not None

# end function


@pytest.mark.parametrize(
    "mod_name",
    [
        "pyoti.core",
        "pyoti.sparse",
        "pyoti.dense",
        "pyoti.real",
        "pyoti.fem",
        "pyoti.whereotilib",
    ],
)
def test_import_core_submodules(mod_name: str):
    """
    Test importing all core Cython / Python submodules.

    Parameters
    ----------
    mod_name : str
        Name of the module to import.
    """
    mod = importlib.import_module(mod_name)
    assert mod is not None

# end function


@pytest.mark.parametrize(
    "sm",
    [
        "onumm1n1",
        "onumm1n2",
        "onumm1n3",
        "onumm1n4",
        "onumm1n10",
        "onumm1n20",
        "onumm1n30",
        "onumm2n1",
        "onumm2n2",
        "onumm2n3",
        "onumm2n4",
        "onumm3n1",
        "onumm3n2",
        "onumm3n3",
        "onumm3n4",
        "onumm10n1",
        "onumm10n2",
    ],
)
def test_import_static_modules(sm: str):
    """
    Test importing all precompiled static dense submodules.

    Parameters
    ----------
    sm : str
        Name of the static module to import.
    """
    mod = importlib.import_module(f"pyoti.static.{sm}")
    cls = getattr(mod, sm, None)
    assert cls is not None, f"Class {sm} not found in pyoti.static.{sm}"

# end function


def test_precomputed_data_available():
    """
    Verify that precomputed data tables generated by 'make gendata' exist and
    load.
    """
    import pyoti.whereotilib as w

    lib_path = w.getpath()
    data_dir = os.path.normpath(os.path.join(lib_path, "..", "data"))
    assert os.path.isdir(data_dir), (
        f"Precomputed data directory not found at {data_dir}. "
        + "Run 'make gendata' in build/."
    )
    sample_file = os.path.join(data_dir, "ndirs_n1.npy")
    assert os.path.isfile(sample_file), (
        f"Required lookup table {sample_file} not found. "+
        "Run 'make gendata' in build/."
    )
    loaded = np.load(sample_file)
    assert len(loaded) > 0

# end function


if __name__ == "__main__":

    pytest.main([__file__])

# end if
