MODULE OTIM35N1

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP         = 8
  INTEGER, PARAMETER :: NUM_IM_DIR = 36
  INTEGER, PARAMETER :: TORDER     = 1

  TYPE ONUMM35N1
    ! Real
    REAL(DP) :: R
    ! Order 1
    REAL(DP) :: E1
    REAL(DP) :: E2
    REAL(DP) :: E3
    REAL(DP) :: E4
    REAL(DP) :: E5
    REAL(DP) :: E6
    REAL(DP) :: E7
    REAL(DP) :: E8
    REAL(DP) :: E9
    REAL(DP) :: EA
    REAL(DP) :: EB
    REAL(DP) :: EC
    REAL(DP) :: ED
    REAL(DP) :: EE
    REAL(DP) :: EF
    REAL(DP) :: EG
    REAL(DP) :: EH
    REAL(DP) :: EI
    REAL(DP) :: EJ
    REAL(DP) :: EK
    REAL(DP) :: EL
    REAL(DP) :: EM
    REAL(DP) :: EN
    REAL(DP) :: EO
    REAL(DP) :: EP
    REAL(DP) :: EQ
    REAL(DP) :: ER
    REAL(DP) :: ES
    REAL(DP) :: ET
    REAL(DP) :: EU
    REAL(DP) :: EV
    REAL(DP) :: EW
    REAL(DP) :: EX
    REAL(DP) :: EY
    REAL(DP) :: EZ
  END TYPE ONUMM35N1

  INTERFACE OPERATOR(*)
    MODULE PROCEDURE ONUMM35N1_MUL_ONUMM35N1,R_MUL_ONUMM35N1,ONUMM35N1_MUL_R
  END INTERFACE

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE ONUMM35N1_ADD_ONUMM35N1,R_ADD_ONUMM35N1,ONUMM35N1_ADD_R
  END INTERFACE

  INTERFACE OPERATOR(-)
    MODULE PROCEDURE ONUMM35N1_NEG,ONUMM35N1_SUB_ONUMM35N1,R_SUB_ONUMM35N1,ONUMM35N1_SUB_R
  END INTERFACE

  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE ONUMM35N1_ASSIGN_R
  END INTERFACE

  INTERFACE TRANSPOSE
    MODULE PROCEDURE ONUMM35N1_TRANSPOSE
  END INTERFACE

  INTERFACE MATMUL
    MODULE PROCEDURE ONUMM35N1_MATMUL_ONUMM35N1,R_MATMUL_ONUMM35N1,ONUMM35N1_MATMUL_R
  END INTERFACE

  CONTAINS

  ELEMENTAL SUBROUTINE ONUMM35N1_ASSIGN_R(RES,LHS)
    
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1), INTENT(OUT) :: RES 

    ! Assign like function 'LHS'
    ! Real
    RES%R = LHS
    ! Order 1
    RES%E1 = 0.0_dp
    RES%E2 = 0.0_dp
    RES%E3 = 0.0_dp
    RES%E4 = 0.0_dp
    RES%E5 = 0.0_dp
    RES%E6 = 0.0_dp
    RES%E7 = 0.0_dp
    RES%E8 = 0.0_dp
    RES%E9 = 0.0_dp
    RES%EA = 0.0_dp
    RES%EB = 0.0_dp
    RES%EC = 0.0_dp
    RES%ED = 0.0_dp
    RES%EE = 0.0_dp
    RES%EF = 0.0_dp
    RES%EG = 0.0_dp
    RES%EH = 0.0_dp
    RES%EI = 0.0_dp
    RES%EJ = 0.0_dp
    RES%EK = 0.0_dp
    RES%EL = 0.0_dp
    RES%EM = 0.0_dp
    RES%EN = 0.0_dp
    RES%EO = 0.0_dp
    RES%EP = 0.0_dp
    RES%EQ = 0.0_dp
    RES%ER = 0.0_dp
    RES%ES = 0.0_dp
    RES%ET = 0.0_dp
    RES%EU = 0.0_dp
    RES%EV = 0.0_dp
    RES%EW = 0.0_dp
    RES%EX = 0.0_dp
    RES%EY = 0.0_dp
    RES%EZ = 0.0_dp

  END SUBROUTINE ONUMM35N1_ASSIGN_R

  ELEMENTAL FUNCTION ONUMM35N1_ADD_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS%R
    ! Order 1
    RES%E1 = LHS%E1 + RHS%E1
    RES%E2 = LHS%E2 + RHS%E2
    RES%E3 = LHS%E3 + RHS%E3
    RES%E4 = LHS%E4 + RHS%E4
    RES%E5 = LHS%E5 + RHS%E5
    RES%E6 = LHS%E6 + RHS%E6
    RES%E7 = LHS%E7 + RHS%E7
    RES%E8 = LHS%E8 + RHS%E8
    RES%E9 = LHS%E9 + RHS%E9
    RES%EA = LHS%EA + RHS%EA
    RES%EB = LHS%EB + RHS%EB
    RES%EC = LHS%EC + RHS%EC
    RES%ED = LHS%ED + RHS%ED
    RES%EE = LHS%EE + RHS%EE
    RES%EF = LHS%EF + RHS%EF
    RES%EG = LHS%EG + RHS%EG
    RES%EH = LHS%EH + RHS%EH
    RES%EI = LHS%EI + RHS%EI
    RES%EJ = LHS%EJ + RHS%EJ
    RES%EK = LHS%EK + RHS%EK
    RES%EL = LHS%EL + RHS%EL
    RES%EM = LHS%EM + RHS%EM
    RES%EN = LHS%EN + RHS%EN
    RES%EO = LHS%EO + RHS%EO
    RES%EP = LHS%EP + RHS%EP
    RES%EQ = LHS%EQ + RHS%EQ
    RES%ER = LHS%ER + RHS%ER
    RES%ES = LHS%ES + RHS%ES
    RES%ET = LHS%ET + RHS%ET
    RES%EU = LHS%EU + RHS%EU
    RES%EV = LHS%EV + RHS%EV
    RES%EW = LHS%EW + RHS%EW
    RES%EX = LHS%EX + RHS%EX
    RES%EY = LHS%EY + RHS%EY
    RES%EZ = LHS%EZ + RHS%EZ

  END FUNCTION ONUMM35N1_ADD_ONUMM35N1

  ELEMENTAL FUNCTION R_ADD_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R
    ! Order 1
    RES%E1 =  + RHS%E1
    RES%E2 =  + RHS%E2
    RES%E3 =  + RHS%E3
    RES%E4 =  + RHS%E4
    RES%E5 =  + RHS%E5
    RES%E6 =  + RHS%E6
    RES%E7 =  + RHS%E7
    RES%E8 =  + RHS%E8
    RES%E9 =  + RHS%E9
    RES%EA =  + RHS%EA
    RES%EB =  + RHS%EB
    RES%EC =  + RHS%EC
    RES%ED =  + RHS%ED
    RES%EE =  + RHS%EE
    RES%EF =  + RHS%EF
    RES%EG =  + RHS%EG
    RES%EH =  + RHS%EH
    RES%EI =  + RHS%EI
    RES%EJ =  + RHS%EJ
    RES%EK =  + RHS%EK
    RES%EL =  + RHS%EL
    RES%EM =  + RHS%EM
    RES%EN =  + RHS%EN
    RES%EO =  + RHS%EO
    RES%EP =  + RHS%EP
    RES%EQ =  + RHS%EQ
    RES%ER =  + RHS%ER
    RES%ES =  + RHS%ES
    RES%ET =  + RHS%ET
    RES%EU =  + RHS%EU
    RES%EV =  + RHS%EV
    RES%EW =  + RHS%EW
    RES%EX =  + RHS%EX
    RES%EY =  + RHS%EY
    RES%EZ =  + RHS%EZ

  END FUNCTION R_ADD_ONUMM35N1

  ELEMENTAL FUNCTION ONUMM35N1_ADD_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3
    RES%E4 = LHS%E4
    RES%E5 = LHS%E5
    RES%E6 = LHS%E6
    RES%E7 = LHS%E7
    RES%E8 = LHS%E8
    RES%E9 = LHS%E9
    RES%EA = LHS%EA
    RES%EB = LHS%EB
    RES%EC = LHS%EC
    RES%ED = LHS%ED
    RES%EE = LHS%EE
    RES%EF = LHS%EF
    RES%EG = LHS%EG
    RES%EH = LHS%EH
    RES%EI = LHS%EI
    RES%EJ = LHS%EJ
    RES%EK = LHS%EK
    RES%EL = LHS%EL
    RES%EM = LHS%EM
    RES%EN = LHS%EN
    RES%EO = LHS%EO
    RES%EP = LHS%EP
    RES%EQ = LHS%EQ
    RES%ER = LHS%ER
    RES%ES = LHS%ES
    RES%ET = LHS%ET
    RES%EU = LHS%EU
    RES%EV = LHS%EV
    RES%EW = LHS%EW
    RES%EX = LHS%EX
    RES%EY = LHS%EY
    RES%EZ = LHS%EZ

  END FUNCTION ONUMM35N1_ADD_R

  ELEMENTAL FUNCTION ONUMM35N1_NEG(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1) :: RES 

    ! Negation like function '-LHS'
    ! Real
    RES%R = -LHS%R
    ! Order 1
    RES%E1 = -LHS%E1
    RES%E2 = -LHS%E2
    RES%E3 = -LHS%E3
    RES%E4 = -LHS%E4
    RES%E5 = -LHS%E5
    RES%E6 = -LHS%E6
    RES%E7 = -LHS%E7
    RES%E8 = -LHS%E8
    RES%E9 = -LHS%E9
    RES%EA = -LHS%EA
    RES%EB = -LHS%EB
    RES%EC = -LHS%EC
    RES%ED = -LHS%ED
    RES%EE = -LHS%EE
    RES%EF = -LHS%EF
    RES%EG = -LHS%EG
    RES%EH = -LHS%EH
    RES%EI = -LHS%EI
    RES%EJ = -LHS%EJ
    RES%EK = -LHS%EK
    RES%EL = -LHS%EL
    RES%EM = -LHS%EM
    RES%EN = -LHS%EN
    RES%EO = -LHS%EO
    RES%EP = -LHS%EP
    RES%EQ = -LHS%EQ
    RES%ER = -LHS%ER
    RES%ES = -LHS%ES
    RES%ET = -LHS%ET
    RES%EU = -LHS%EU
    RES%EV = -LHS%EV
    RES%EW = -LHS%EW
    RES%EX = -LHS%EX
    RES%EY = -LHS%EY
    RES%EZ = -LHS%EZ

  END FUNCTION ONUMM35N1_NEG

  ELEMENTAL FUNCTION ONUMM35N1_SUB_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS%R
    ! Order 1
    RES%E1 = LHS%E1 - RHS%E1
    RES%E2 = LHS%E2 - RHS%E2
    RES%E3 = LHS%E3 - RHS%E3
    RES%E4 = LHS%E4 - RHS%E4
    RES%E5 = LHS%E5 - RHS%E5
    RES%E6 = LHS%E6 - RHS%E6
    RES%E7 = LHS%E7 - RHS%E7
    RES%E8 = LHS%E8 - RHS%E8
    RES%E9 = LHS%E9 - RHS%E9
    RES%EA = LHS%EA - RHS%EA
    RES%EB = LHS%EB - RHS%EB
    RES%EC = LHS%EC - RHS%EC
    RES%ED = LHS%ED - RHS%ED
    RES%EE = LHS%EE - RHS%EE
    RES%EF = LHS%EF - RHS%EF
    RES%EG = LHS%EG - RHS%EG
    RES%EH = LHS%EH - RHS%EH
    RES%EI = LHS%EI - RHS%EI
    RES%EJ = LHS%EJ - RHS%EJ
    RES%EK = LHS%EK - RHS%EK
    RES%EL = LHS%EL - RHS%EL
    RES%EM = LHS%EM - RHS%EM
    RES%EN = LHS%EN - RHS%EN
    RES%EO = LHS%EO - RHS%EO
    RES%EP = LHS%EP - RHS%EP
    RES%EQ = LHS%EQ - RHS%EQ
    RES%ER = LHS%ER - RHS%ER
    RES%ES = LHS%ES - RHS%ES
    RES%ET = LHS%ET - RHS%ET
    RES%EU = LHS%EU - RHS%EU
    RES%EV = LHS%EV - RHS%EV
    RES%EW = LHS%EW - RHS%EW
    RES%EX = LHS%EX - RHS%EX
    RES%EY = LHS%EY - RHS%EY
    RES%EZ = LHS%EZ - RHS%EZ

  END FUNCTION ONUMM35N1_SUB_ONUMM35N1

  ELEMENTAL FUNCTION R_SUB_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R
    ! Order 1
    RES%E1 =  - RHS%E1
    RES%E2 =  - RHS%E2
    RES%E3 =  - RHS%E3
    RES%E4 =  - RHS%E4
    RES%E5 =  - RHS%E5
    RES%E6 =  - RHS%E6
    RES%E7 =  - RHS%E7
    RES%E8 =  - RHS%E8
    RES%E9 =  - RHS%E9
    RES%EA =  - RHS%EA
    RES%EB =  - RHS%EB
    RES%EC =  - RHS%EC
    RES%ED =  - RHS%ED
    RES%EE =  - RHS%EE
    RES%EF =  - RHS%EF
    RES%EG =  - RHS%EG
    RES%EH =  - RHS%EH
    RES%EI =  - RHS%EI
    RES%EJ =  - RHS%EJ
    RES%EK =  - RHS%EK
    RES%EL =  - RHS%EL
    RES%EM =  - RHS%EM
    RES%EN =  - RHS%EN
    RES%EO =  - RHS%EO
    RES%EP =  - RHS%EP
    RES%EQ =  - RHS%EQ
    RES%ER =  - RHS%ER
    RES%ES =  - RHS%ES
    RES%ET =  - RHS%ET
    RES%EU =  - RHS%EU
    RES%EV =  - RHS%EV
    RES%EW =  - RHS%EW
    RES%EX =  - RHS%EX
    RES%EY =  - RHS%EY
    RES%EZ =  - RHS%EZ

  END FUNCTION R_SUB_ONUMM35N1

  ELEMENTAL FUNCTION ONUMM35N1_SUB_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS
    ! Order 1
    RES%E1 = LHS%E1
    RES%E2 = LHS%E2
    RES%E3 = LHS%E3
    RES%E4 = LHS%E4
    RES%E5 = LHS%E5
    RES%E6 = LHS%E6
    RES%E7 = LHS%E7
    RES%E8 = LHS%E8
    RES%E9 = LHS%E9
    RES%EA = LHS%EA
    RES%EB = LHS%EB
    RES%EC = LHS%EC
    RES%ED = LHS%ED
    RES%EE = LHS%EE
    RES%EF = LHS%EF
    RES%EG = LHS%EG
    RES%EH = LHS%EH
    RES%EI = LHS%EI
    RES%EJ = LHS%EJ
    RES%EK = LHS%EK
    RES%EL = LHS%EL
    RES%EM = LHS%EM
    RES%EN = LHS%EN
    RES%EO = LHS%EO
    RES%EP = LHS%EP
    RES%EQ = LHS%EQ
    RES%ER = LHS%ER
    RES%ES = LHS%ES
    RES%ET = LHS%ET
    RES%EU = LHS%EU
    RES%EV = LHS%EV
    RES%EW = LHS%EW
    RES%EX = LHS%EX
    RES%EY = LHS%EY
    RES%EZ = LHS%EZ

  END FUNCTION ONUMM35N1_SUB_R

  ELEMENTAL FUNCTION ONUMM35N1_MUL_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS%R*RHS%R
    ! Order 1
    RES%E1 = LHS%R*RHS%E1 + LHS%E1*RHS%R
    RES%E2 = LHS%R*RHS%E2 + LHS%E2*RHS%R
    RES%E3 = LHS%R*RHS%E3 + LHS%E3*RHS%R
    RES%E4 = LHS%R*RHS%E4 + LHS%E4*RHS%R
    RES%E5 = LHS%R*RHS%E5 + LHS%E5*RHS%R
    RES%E6 = LHS%R*RHS%E6 + LHS%E6*RHS%R
    RES%E7 = LHS%R*RHS%E7 + LHS%E7*RHS%R
    RES%E8 = LHS%R*RHS%E8 + LHS%E8*RHS%R
    RES%E9 = LHS%R*RHS%E9 + LHS%E9*RHS%R
    RES%EA = LHS%R*RHS%EA + LHS%EA*RHS%R
    RES%EB = LHS%R*RHS%EB + LHS%EB*RHS%R
    RES%EC = LHS%R*RHS%EC + LHS%EC*RHS%R
    RES%ED = LHS%R*RHS%ED + LHS%ED*RHS%R
    RES%EE = LHS%R*RHS%EE + LHS%EE*RHS%R
    RES%EF = LHS%R*RHS%EF + LHS%EF*RHS%R
    RES%EG = LHS%R*RHS%EG + LHS%EG*RHS%R
    RES%EH = LHS%R*RHS%EH + LHS%EH*RHS%R
    RES%EI = LHS%R*RHS%EI + LHS%EI*RHS%R
    RES%EJ = LHS%R*RHS%EJ + LHS%EJ*RHS%R
    RES%EK = LHS%R*RHS%EK + LHS%EK*RHS%R
    RES%EL = LHS%R*RHS%EL + LHS%EL*RHS%R
    RES%EM = LHS%R*RHS%EM + LHS%EM*RHS%R
    RES%EN = LHS%R*RHS%EN + LHS%EN*RHS%R
    RES%EO = LHS%R*RHS%EO + LHS%EO*RHS%R
    RES%EP = LHS%R*RHS%EP + LHS%EP*RHS%R
    RES%EQ = LHS%R*RHS%EQ + LHS%EQ*RHS%R
    RES%ER = LHS%R*RHS%ER + LHS%ER*RHS%R
    RES%ES = LHS%R*RHS%ES + LHS%ES*RHS%R
    RES%ET = LHS%R*RHS%ET + LHS%ET*RHS%R
    RES%EU = LHS%R*RHS%EU + LHS%EU*RHS%R
    RES%EV = LHS%R*RHS%EV + LHS%EV*RHS%R
    RES%EW = LHS%R*RHS%EW + LHS%EW*RHS%R
    RES%EX = LHS%R*RHS%EX + LHS%EX*RHS%R
    RES%EY = LHS%R*RHS%EY + LHS%EY*RHS%R
    RES%EZ = LHS%R*RHS%EZ + LHS%EZ*RHS%R

  END FUNCTION ONUMM35N1_MUL_ONUMM35N1

  ELEMENTAL FUNCTION R_MUL_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS*RHS%R
    ! Order 1
    RES%E1 = LHS*RHS%E1
    RES%E2 = LHS*RHS%E2
    RES%E3 = LHS*RHS%E3
    RES%E4 = LHS*RHS%E4
    RES%E5 = LHS*RHS%E5
    RES%E6 = LHS*RHS%E6
    RES%E7 = LHS*RHS%E7
    RES%E8 = LHS*RHS%E8
    RES%E9 = LHS*RHS%E9
    RES%EA = LHS*RHS%EA
    RES%EB = LHS*RHS%EB
    RES%EC = LHS*RHS%EC
    RES%ED = LHS*RHS%ED
    RES%EE = LHS*RHS%EE
    RES%EF = LHS*RHS%EF
    RES%EG = LHS*RHS%EG
    RES%EH = LHS*RHS%EH
    RES%EI = LHS*RHS%EI
    RES%EJ = LHS*RHS%EJ
    RES%EK = LHS*RHS%EK
    RES%EL = LHS*RHS%EL
    RES%EM = LHS*RHS%EM
    RES%EN = LHS*RHS%EN
    RES%EO = LHS*RHS%EO
    RES%EP = LHS*RHS%EP
    RES%EQ = LHS*RHS%EQ
    RES%ER = LHS*RHS%ER
    RES%ES = LHS*RHS%ES
    RES%ET = LHS*RHS%ET
    RES%EU = LHS*RHS%EU
    RES%EV = LHS*RHS%EV
    RES%EW = LHS*RHS%EW
    RES%EX = LHS*RHS%EX
    RES%EY = LHS*RHS%EY
    RES%EZ = LHS*RHS%EZ

  END FUNCTION R_MUL_ONUMM35N1

  ELEMENTAL FUNCTION ONUMM35N1_MUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM35N1) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS%R*RHS
    ! Order 1
    RES%E1 = LHS%E1*RHS
    RES%E2 = LHS%E2*RHS
    RES%E3 = LHS%E3*RHS
    RES%E4 = LHS%E4*RHS
    RES%E5 = LHS%E5*RHS
    RES%E6 = LHS%E6*RHS
    RES%E7 = LHS%E7*RHS
    RES%E8 = LHS%E8*RHS
    RES%E9 = LHS%E9*RHS
    RES%EA = LHS%EA*RHS
    RES%EB = LHS%EB*RHS
    RES%EC = LHS%EC*RHS
    RES%ED = LHS%ED*RHS
    RES%EE = LHS%EE*RHS
    RES%EF = LHS%EF*RHS
    RES%EG = LHS%EG*RHS
    RES%EH = LHS%EH*RHS
    RES%EI = LHS%EI*RHS
    RES%EJ = LHS%EJ*RHS
    RES%EK = LHS%EK*RHS
    RES%EL = LHS%EL*RHS
    RES%EM = LHS%EM*RHS
    RES%EN = LHS%EN*RHS
    RES%EO = LHS%EO*RHS
    RES%EP = LHS%EP*RHS
    RES%EQ = LHS%EQ*RHS
    RES%ER = LHS%ER*RHS
    RES%ES = LHS%ES*RHS
    RES%ET = LHS%ET*RHS
    RES%EU = LHS%EU*RHS
    RES%EV = LHS%EV*RHS
    RES%EW = LHS%EW*RHS
    RES%EX = LHS%EX*RHS
    RES%EY = LHS%EY*RHS
    RES%EZ = LHS%EZ*RHS

  END FUNCTION ONUMM35N1_MUL_R

  FUNCTION ONUMM35N1_MATMUL_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM35N1) :: TMP 
    TYPE(ONUMM35N1) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION ONUMM35N1_MATMUL_ONUMM35N1

  FUNCTION R_MATMUL_ONUMM35N1(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM35N1), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM35N1) :: TMP 
    TYPE(ONUMM35N1) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION R_MATMUL_ONUMM35N1

  FUNCTION ONUMM35N1_MATMUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS(:,:) 
    REAL(DP), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM35N1) :: TMP 
    TYPE(ONUMM35N1) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION ONUMM35N1_MATMUL_R

  FUNCTION ONUMM35N1_TRANSPOSE(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM35N1), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM35N1) :: RES(SIZE(LHS,2),SIZE(LHS,1)) 
    INTEGER :: I,J 

    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(LHS,2)
        RES( J, I ) = LHS( I, J )
      END DO
    END DO

  END FUNCTION ONUMM35N1_TRANSPOSE

END MODULE OTIM35N1
