MODULE OTIM1N0

  IMPLICIT NONE

  INTEGER, PARAMETER :: DP         = 8
  INTEGER, PARAMETER :: NUM_IM_DIR = 1
  INTEGER, PARAMETER :: TORDER     = 0

  TYPE ONUMM1N0
    ! Real
    REAL(DP) :: R
  END TYPE ONUMM1N0

  INTERFACE OPERATOR(*)
    MODULE PROCEDURE ONUMM1N0_MUL_ONUMM1N0,R_MUL_ONUMM1N0,ONUMM1N0_MUL_R
  END INTERFACE

  INTERFACE OPERATOR(+)
    MODULE PROCEDURE ONUMM1N0_ADD_ONUMM1N0,R_ADD_ONUMM1N0,ONUMM1N0_ADD_R
  END INTERFACE

  INTERFACE OPERATOR(-)
    MODULE PROCEDURE ONUMM1N0_NEG,ONUMM1N0_SUB_ONUMM1N0,R_SUB_ONUMM1N0,ONUMM1N0_SUB_R
  END INTERFACE

  INTERFACE ASSIGNMENT(=)
    MODULE PROCEDURE ONUMM1N0_ASSIGN_R
  END INTERFACE

  INTERFACE TRANSPOSE
    MODULE PROCEDURE ONUMM1N0_TRANSPOSE
  END INTERFACE

  INTERFACE MATMUL
    MODULE PROCEDURE ONUMM1N0_MATMUL_ONUMM1N0,R_MATMUL_ONUMM1N0,ONUMM1N0_MATMUL_R
  END INTERFACE

  CONTAINS

  ELEMENTAL SUBROUTINE ONUMM1N0_ASSIGN_R(RES,LHS)
    
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0), INTENT(OUT) :: RES 

    ! Assign like function 'LHS'
    ! Real
    RES%R = LHS

  END SUBROUTINE ONUMM1N0_ASSIGN_R

  ELEMENTAL FUNCTION ONUMM1N0_ADD_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS%R

  END FUNCTION ONUMM1N0_ADD_ONUMM1N0

  ELEMENTAL FUNCTION R_ADD_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS + RHS%R

  END FUNCTION R_ADD_ONUMM1N0

  ELEMENTAL FUNCTION ONUMM1N0_ADD_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Addition like function 'LHS + RHS'
    ! Real
    RES%R = LHS%R + RHS

  END FUNCTION ONUMM1N0_ADD_R

  ELEMENTAL FUNCTION ONUMM1N0_NEG(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0) :: RES 

    ! Negation like function '-LHS'
    ! Real
    RES%R = -LHS%R

  END FUNCTION ONUMM1N0_NEG

  ELEMENTAL FUNCTION ONUMM1N0_SUB_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS%R

  END FUNCTION ONUMM1N0_SUB_ONUMM1N0

  ELEMENTAL FUNCTION R_SUB_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS - RHS%R

  END FUNCTION R_SUB_ONUMM1N0

  ELEMENTAL FUNCTION ONUMM1N0_SUB_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Addition like function 'LHS - RHS'
    ! Real
    RES%R = LHS%R - RHS

  END FUNCTION ONUMM1N0_SUB_R

  ELEMENTAL FUNCTION ONUMM1N0_MUL_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS%R*RHS%R

  END FUNCTION ONUMM1N0_MUL_ONUMM1N0

  ELEMENTAL FUNCTION R_MUL_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS*RHS%R

  END FUNCTION R_MUL_ONUMM1N0

  ELEMENTAL FUNCTION ONUMM1N0_MUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS 
    REAL(DP), INTENT(IN) :: RHS 
    TYPE(ONUMM1N0) :: RES 

    ! Multiplication like function 'LHS*RHS'
    ! Real
    RES%R = LHS%R*RHS

  END FUNCTION ONUMM1N0_MUL_R

  FUNCTION ONUMM1N0_MATMUL_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM1N0) :: TMP 
    TYPE(ONUMM1N0) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION ONUMM1N0_MATMUL_ONUMM1N0

  FUNCTION R_MATMUL_ONUMM1N0(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    REAL(DP), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM1N0), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM1N0) :: TMP 
    TYPE(ONUMM1N0) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION R_MATMUL_ONUMM1N0

  FUNCTION ONUMM1N0_MATMUL_R(LHS,RHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS(:,:) 
    REAL(DP), INTENT(IN) :: RHS(:,:) 
    TYPE(ONUMM1N0) :: TMP 
    TYPE(ONUMM1N0) :: RES(SIZE(LHS,1),SIZE(RHS,2)) 
    INTEGER :: I,J,K 

    ! Dimension check
    IF (SIZE(LHS,2) /= SIZE(RHS,1)) THEN
      STOP "Runtime error: " // &
           "Dimension mismatch in MATMUL."
    END IF
    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(RHS,2)
        TMP = 0.0_DP
        DO K = 1, SIZE(LHS,2)
          TMP = TMP + LHS( I, K )*RHS( K, J )
        END DO
        RES( I, J ) = TMP
      END DO
    END DO

  END FUNCTION ONUMM1N0_MATMUL_R

  FUNCTION ONUMM1N0_TRANSPOSE(LHS)&
    RESULT(RES)
    IMPLICIT NONE
    TYPE(ONUMM1N0), INTENT(IN) :: LHS(:,:) 
    TYPE(ONUMM1N0) :: RES(SIZE(LHS,2),SIZE(LHS,1)) 
    INTEGER :: I,J 

    DO I = 1, SIZE(LHS,1)
      DO J = 1, SIZE(LHS,2)
        RES( J, I ) = LHS( I, J )
      END DO
    END DO

  END FUNCTION ONUMM1N0_TRANSPOSE

END MODULE OTIM1N0
