#ifndef OTI_LIBRARY_H
#define OTI_LIBRARY_H

// ----------------------------------------------------------------------------------------------------
// ---------------------------------     EXTERNAL LIBRARIES     ---------------------------------------
// ----------------------------------------------------------------------------------------------------

// Library version (generated by CMake from include/oti/version.h.in).
#include "oti/version.h"

// Core functions.
#include "oti/core.h"
#include "oti/real.h"
// #include "oti/complex.h"

// Algebras.
#include "oti/dense.h"
#include "oti/sparse.h"
// #include "oti/semisparse.h"

// Multidual
#include "oti/static.h"

// FEM support.
#include "oti/fem.h"

// ----------------------------------------------------------------------------------------------------
// --------------------------------    END EXTERNAL LIBRARIES     -------------------------------------
// ----------------------------------------------------------------------------------------------------

#endif