

# Runtime version queries of the compiled C library. The header is generated by CMake into the build
# tree from include/oti/version.h.in, so it is resolved through the generated include directory that
# setup.py adds to the extension include paths.
cdef extern from "oti/version.h" nogil:

  const char* oti_version()
  int         oti_version_number()
  void        oti_version_numbers(int* major, int* minor, int* patch)
